### ISSUE TITLE
Properly handle DIA imports

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#10]
There are some rare issues with VS2015 update 1 and DIA.
Christian, can you provide the error message please?

**Comment by csoltenborn** [comment]
Error message when executing tests locally:

System.IO.FileNotFoundException: Die COM-Klassenfactory für die Komponente mit CLSID {3BFCEA48-620F-4B6B-81F7-B9AF75454C7D} konnte aufgrund des folgenden Fehlers nicht abgerufen werden: 8007007e Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E).

**Comment by jgefele** [comment]
Just for the record, with the current build (0.2.2.181) which uses an updated DIA DLL it fails in Visual Studio 2013 with the following message:

An exception occurred while test discoverer 'TestDiscoverer' was loading tests. Exception: Retrieving the COM class factory for component with CLSID {E6756135-1E65-4D17-8576-610761398C3C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
