### ISSUE TITLE
Not all tests discovered

### ISSUE THREAD

**Issue by Alfred5020** [csoltenborn/GoogleTestAdapter#11]
Hi!
I detecting a problem with typed tests. They are not discovered

Output:
Found 306 tests in executable C:\Source\zenon\Supervisor\main\BIN\PC\UTests\PROGRAMFILES32\DebugNoUTest\zenon32misc_net_UTest.exe
Warning: Could not find source location for test Typed/fixCCommandReactionsForNetModule/0.Process_ForwardsCallToConcreteImplementation_Yes
Warning: Could not find source location for test Typed/fixCCommandReactionsForNetModule/1.Process_ForwardsCallToConcreteImplementation_Yes
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.AktionAnstossen_NewCommand_HandlerCalled
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.AktionAnstossen_WithOutCommandInstance_NoCrash
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.Serialize_HappyPath_SameAsWritten
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.Serialize_WithOutCommandInstance_NoCrash
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.Info_HappyPath_Filled
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.Info_WithOutCommandInstance_NoCrash
And so on

At least 262 test cases are detected and executed only 250!?
Output:
Many other …
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/5.AddLogEntry_HappyPath_Filled
Running 250 tests...
Test execution completed.

Thanks for any suggestion!
Alfred

**Comment by jgefele** [comment]
Hi Alfred,

thank you for your bug report.

I have just tried typed tests (never used those before) and they seem to work in general. Just the source location is not found (#12). Thanks for pointing us to this issue.

Did you click "run all" or something else?

Where does the number "at least 262 tests" come from? In the logs I just see "Found 306 tests in executable" and "Running 250 tests". Can you provide the full output with all "Warning" lines removed?

It would be great help if you could provide some minimal example code and upload it here.


Cheers,
Jonas

**Comment by Alfred5020** [comment]
Hi Jonas!
I run only the tests of one Project. In my example this is Archive_utest. This is a small ut -Testproject. The defect was recognized with a larger one.
The output is:
------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
Archiv_UTest.exe is built for Framework None and Platform X64.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
Found 14 tests in executable C:\Source\zenon\Supervisor\main\BIN\PC\UTests\PROGRAMFILES64\DebugNoUTest\Archiv_UTest.exe
Warning: Could not find source location for test FooTest/0.DoesBlah
Warning: Could not find source location for test FooTest/1.DoesBlah
Warning: Could not find source location for test FooTest/2.DoesBlah
Warning: Could not find source location for test Typed/fixCCommandReactionsForNetModule/0.Process_ForwardsCallToConcreteImplementation_Yes
Warning: Could not find source location for test Typed/fixCCommandReactionsForNetModule/1.Process_ForwardsCallToConcreteImplementation_Yes
========== Discover test finished: 14 found (0:00:00,1440144) ==========
------ Run test started ------
Found 14 tests in executable C:\Source\zenon\Supervisor\main\BIN\PC\UTests\PROGRAMFILES64\DebugNoUTest\Archiv_UTest.exe
Warning: Could not find source location for test FooTest/0.DoesBlah
Warning: Could not find source location for test FooTest/1.DoesBlah
Warning: Could not find source location for test FooTest/2.DoesBlah
Warning: Could not find source location for test Typed/fixCCommandReactionsForNetModule/0.Process_ForwardsCallToConcreteImplementation_Yes
Warning: Could not find source location for test Typed/fixCCommandReactionsForNetModule/1.Process_ForwardsCallToConcreteImplementation_Yes
Running 8 tests...
Test execution completed.
========== Run test finished: 8 run (0:00:01,3231323) ==========
The sample file TypedTest_test.TXT (cpp) covers all 3 errors
a.	TYPED_TEST DoesBlah taken from the documentation is not detected. Already mentioned in your defect #12
b.	TYPED_TEST_CASE_P already mentioned in your defect #12
c.	TEST_P(StoreRetConsidered4Numbers_fixCRatedNetConfig, _IsSetINIResultConsidered_ResultFollowSetINIResult) detected but not executed

I hope this will help to find the bugs. Thank you to develop and maintain this test adapter!
Best regards
Alfred

[TypedTest_test.TXT](https://github.com/csoltenborn/GoogleTestAdapter/files/66519/TypedTest_test.TXT)

**Comment by jgefele** [comment]
Hi Alfred,

thank you for this example. I can reproduce the issue.

Note to self (and Christian):

* replace include "stdafx.h" by "gtest/gtest.h" and "Windows.h"
* "Run all" results in:

```
Running 6 tests...
...
Test adapter sent back a result for an unknown test case. Ignoring result for 'VerifyStoreFailDetected_param/StoreRetConsidered4Numbers_fixCRatedNetConfig._IsSetINIResultConsidered_ResultFollowSetINIResult/0 [(001AE520 pointing to L"Any", false)]'.
========== Run test finished: 5 run (0:00:05,4408968) ==========
```

* Selecting "VerifyStoreFailDetected_..." test and "Run selected tests" results in

```
------ Run test started ------
========== Run test finished: 0 run (0:00:00,1300868) ==========
```

**Comment by jgefele** [comment]
Hi Alfred,

issues #11 and #12 are fixed now.

If you are using Visual Studio 2015, you can give the development build a try:
 * Tools -> Extensions and Updates -> Google Test Adapter -> Uninstall
 * Close Visual Studio
 * Download and double click the [GoogleTestAdapter.vsix from our CI Server](https://ci.appveyor.com/api/buildjobs/6etk83qf3qpu0a9b/artifacts/GoogleTestExtension/GoogleTestAdapterVSIX/bin/Release/GoogleTestAdapter-0.2.2.vsix).
 * Start Visual Studio

If you are using Visual Studio 2013 you'll have to wait till issue #10 is fixed as well (it's next on my list), because right now the development build is broken for VS2013.

If you're happy with the Google Test Adapter you can make us happy with a positive review in the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/94c02701-8043-4851-8458-34f137d10874) `;-)`.

Cheers,
Jonas
