### ISSUE TITLE
Experimental test execution framework: wrong crash detection

### ISSUE THREAD

**Issue by gobater** [csoltenborn/GoogleTestAdapter#110]
Since the latest update of "Google Test Adapter" (v0.9.0.635), the new test execution framework (experimental) is enabled by default.

This framework wrongly detects my PASSED tests as FAILED and prints the message "!! This test has probably CRASHED !!"
Using the "old test framework" (disabling the experimental framework) recognizes the test as PASSED.
I am using VS2015 Update 3.

Raw output of google test follows

```
>>>>>>>>>>>>>>> Output of command '<FILE_PATH>\<EXE_FILE>.exe --gtest_output="xml:C:\Users\xxx\AppData\Local\Temp\tmpFD1E.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 --gtest_filter=TrackableDevice_P.RunWhenEnabled/1'
Running main() from gmock_main.cc
Note: Google Test filter = TrackableDevice_P.RunWhenEnabled/1
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TrackableDevice_P
[ RUN      ] TrackableDevice_P.RunWhenEnabled/1
⁣
GMOCK WARNING:
<FILE_PATH>\<FILE_NAME>.cpp(2420): Too many actions specified in EXPECT_CALL( <MOCK_OBJECT>, <MOCK_METHOD>)...
Expected to be never called, but has 0 WillOnce()s and a WillRepeatedly().[       OK ] TrackableDevice_P.RunWhenEnabled/1 (62 ms)
[----------] 1 test from TrackableDevice_P (62 ms total)
⁣
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (62 ms total)
[  PASSED  ] 1 test.
<<<<<<<<<<<<<<< End of Output
Google Test execution completed, overall duration: 00:00:01.6919126.
========== Run test finished: 1 run (0:00:01,729) ==========
```

**Comment by csoltenborn** [comment]
Thanks for your feedback and for the raw output! Can you please also attach the debug output of GTA?

**Comment by csoltenborn** [comment]
I think we have found the issue already - if this is not the case, we will come back to you. Until then, you don't need to put any effort into this...

**Comment by gobater** [comment]
Yes, sorry. I provided the output of the GTA (not the raw output).

The issue is present only with the new execution framework, the old just works fine. I will provide you the output of the command line piped to a file per email.

**Comment by csoltenborn** [comment]
Can you give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.9.0.636/artifacts) a try? The issue was that the new execution framework could not deal with test output not ending with a line break - we assumed the `[ OK ] ...` part to always be at the beginning of the line.

**Comment by gobater** [comment]
The supplied build works perfectly with the **new** test execution framework (and old).
Thank you very much for your fast feedback and build

**Comment by csoltenborn** [comment]
You are welcome! We'll wait a couple of days to see if there are more issues with v0.9.0, and will probably release the fix at the beginning of next week...
