### ISSUE TITLE
Available for Visual Studio Express 2013?

### ISSUE THREAD

**Issue by fporras-galvez** [csoltenborn/GoogleTestAdapter#111]
I'm using Visual Studio Express 2013 and I tried to install Google Test Adapter extension from Visual Studio Gallery but I can't find it. 

On the other hand, I have also installed Visual Studio 2015 as trial version and in this case Google Test Adapter is indeed displayed in the Visual Studio Gallery.

Thanks and regards.

**Comment by csoltenborn** [comment]
This is not a limitation of GTA, but of the Express editions of Visual Studio - see e.g. [here](http://superuser.com/questions/677930/cant-install-vsix-extension-file-in-visual-studio-express-2013)... Community editions (including 2015) should be fine, though, so maybe this is an option for you!?

**Comment by fporras-galvez** [comment]
Yes, I installed VS 2015 Community Edition and I found the extension.

Thanks.

**Comment by csoltenborn** [comment]
You're welcome!
