### ISSUE TITLE
GoogleTestAdapter cannot find test in the solution

### ISSUE THREAD

**Issue by kamakay** [csoltenborn/GoogleTestAdapter#113]
Hi,

I have created a simple win32 console application and then added test using google test. When running "Test -> Run All" the output console states "Discover test finished: 0 found ".

I am using Visuatl Studio Community 2015.

**Comment by csoltenborn** [comment]
Have you already checked out our [trouble shooting](https://github.com/csoltenborn/GoogleTestAdapter#trouble_shooting) section?

**Comment by kamakay** [comment]
Done, found that your are driving test reserach using a specific regex, thanks!
