### ISSUE TITLE
No source locations for typed tests and type-parameterized tests.

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#12]
We don't find source location for [typed tests](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#typed-tests) and [type-parameterized tests](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#type-parameterized-tests).

		class MyStrangeArray : public std::array<int, 3>
		{
		public:  MyStrangeArray(std::initializer_list<int> init) : array({ 3,2,1 }) {}
		};

		template< typename int_container_type >
		class TypedTests : public ::testing::Test {
		public:
			typename int_container_type container{ 1,2,3 };
		};

		typedef ::testing::Types<std::vector<int>, std::array<int,3>, MyStrangeArray> IntContainerTypes;
		TYPED_TEST_CASE(TypedTests, IntContainerTypes);

		TYPED_TEST(TypedTests, CanIterate) {
			int sum = 0;
			for (int value : this->container)
				sum += value;
			EXPECT_EQ(1 + 2 + 3, sum);
		}

		TYPED_TEST(TypedTests, CanDefeatMath) {
			EXPECT_NE(this->container[0] + this->container[1], this->container[2]);
		}

		template< typename int_container_type >
		class TypeParameterizedTests : public TypedTests<int_container_type> {};

		TYPED_TEST_CASE_P(TypeParameterizedTests);

		TYPED_TEST_P(TypeParameterizedTests, CanIterate) {
			int sum = 0;
			for (int value : this->container)
				sum += value;
			EXPECT_EQ(1 + 2 + 3, sum);
		}

		TYPED_TEST_P(TypeParameterizedTests, CanDefeatMath) {
			EXPECT_NE(this->container[0] + this->container[1], this->container[2]);
		}

		REGISTER_TYPED_TEST_CASE_P(TypeParameterizedTests, CanIterate, CanDefeatMath);

		typedef ::testing::Types<std::array<int, 3>, MyStrangeArray> IntArrayTypes;
		INSTANTIATE_TYPED_TEST_CASE_P(Vec, TypeParameterizedTests, std::vector<int>);
		INSTANTIATE_TYPED_TEST_CASE_P(Arr, TypeParameterizedTests, IntArrayTypes);

**Comment by jgefele** [comment]
Just to be clear:  tests are found, can be "run all", or just run a selected group. It's just the source location which is missing.

**Comment by jgefele** [comment]
Fixed by commit 5c2797e

**Comment by Alfred5020** [comment]
Hi!
Thankyou for the fast fix! My provided test cases are now correctly detected and executed! A other bug I have detected related with typed tests. But for this I create a new defect.
Best regards 
Alfred
