### ISSUE TITLE
Test discovery doesn't use correct environment

### ISSUE THREAD

**Issue by tomisaacson** [csoltenborn/GoogleTestAdapter#123]
I have a project that uses Qt. The application and tests all build and run fine but when the adapter attempts to find the tests I get an error:
```
ERROR: Could not list test cases of executable 'C:\UtilsUnitTests.exe': executing process failed with return code -1073741515
Command executed: 'C:\UtilsUnitTests.exe --gtest_list_tests', working directory: 'C:\'
Command produced no output
Found 0 tests in executable C:\\UtilsUnitTests.exe
```
This is because when the executable is run it doesn't know where the Qt Dlls are, even though Visual Studio does. It seems that Googe Test Adapter isn't the same path as Visual Studio to run them.

**Comment by csoltenborn** [comment]
That's true, and there's nothing we can do about that because the VS test framework doesn't provide that information for us. But you can: Please use option *PATH extension* to add your Dlls to the path. See also our [trouble shooting section](https://github.com/csoltenborn/GoogleTestAdapter#trouble-shooting).

**Comment by csoltenborn** [comment]
Since you haven't commented any more, I assume that this indeed solved your problem - otherwise, feel free to reopen!

**Comment by matthewdhunt** [comment]
Could you clarify what you mean by "Please use option PATH extension to add your Dlls to the path."?  Are you saying we must modify system environment variables?  That wouldn't be an option as it would interfere with switching between projects with different Qt versions.
