### ISSUE TITLE
VS2017 ERROR: couldn't find the msdia.dll

### ISSUE THREAD

**Issue by Farwaykorse** [csoltenborn/GoogleTestAdapter#124]
Test discovery returns:

    ERROR: Couldn't find the msdia.dll to parse *.pdb files. You will not get any source locations for your tests.
    Warning: Could not find source location for test testclass.testname

For each pdb and all tests in them.

On this pc only VS2017 is installed.  
My first idea is that the new directory structure might prevent the runner from finding these files.

The test themselves work properly, and return the proper messages. Just without the source links.

Google Test Adapter v0.9.1.653  
VS Community 2017 / 15.0.0.0+26228.1  
.NET v4.6.01586

**Comment by csoltenborn** [comment]
Thanks for your detailed bug report! However, we are not relying on file locations (see [this line](https://github.com/csoltenborn/GoogleTestAdapter/blob/f311375f7b0be9169d4c131e1616a5c5f7a1899d/GoogleTestAdapter/DiaResolver/DiaResolver.cs#L95)), so something else must go wrong...

Can you please verify that your VS installation indeed contains the DIA stuff? Search for `msdia`  within the VS20127 folder...

**Comment by Farwaykorse** [comment]
It seems the files are there. 
https://gist.github.com/Farwaykorse/27e4d854e12b74ecf79a8f198c0929f0

For now I've tried repairing the installation and a second install using 2017 preview with a basic c++ workload.

**Comment by csoltenborn** [comment]
Thanks! Could you please also search for `e6756135-1e65-4d17-8576-610761398c3c` (and maybe also
`3bfcea48-620f-4b6b-81f7-b9af75454c7d`) within your registry? Just in case: Use the `regedit` tool for this... If you do have findings: Are they located within a `CLSID` folder?

Explanation: We are using [CLSIDs](https://msdn.microsoft.com/de-de/library/windows/desktop/ms691424(v=vs.85).aspx) to instantiate the DIA COM objects - they should be made available through the registry. If you do not have any findings, the VS2017 installation has not added them to the registry for some reason. In that case, we will have to investigate the VS2017-only case a bit closer.

**Comment by ninjaCoder** [comment]
I am facing the same error of Couldn't find the msdia.dll to parse...
This error started with the March 14, 2017 - version 15.0 (26228.09) release.
The two values (e6756135-1e65-4d17-8576-610761398c3c and 3bfcea48-620f-4b6b-81f7-b9af75454c7d) are not in the registry.
The problem exist even with the latest release of vs2017 (March 31, 2017 - version 15.0 (26228.12)).

I don't know if this is related or not but when I try to debug any test this is the output:

------ Run test started ------
Google Test Adapter: Test execution starting...
ERROR: Couldn't find the msdia.dll to parse *.pdb files. You will not get any source locations for your tests.
Warning: Could not find source location for test aaa.bbb
Found 1 tests in executable C:\Users\w7pro\Documents\Visual Studio 2017\Projects\ProjectDir\Debug\ConsoleApplication1_Tests.exe
ERROR: Exception while running tests: System.IO.FileNotFoundException: Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GoogleTestAdapter.TestAdapter.Framework.VsDebuggerAttacher..ctor(ILogger logger, Int32 processId)
   at GoogleTestAdapter.TestAdapter.TestExecutor.DoRunTests(IEnumerable`1 allTestCasesInExecutables, ICollection`1 testCasesToRun, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at GoogleTestAdapter.TestAdapter.TestExecutor.TryRunTests(IEnumerable`1 vsTestCasesToRun, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at GoogleTestAdapter.TestAdapter.TestExecutor.RunTests(IEnumerable`1 vsTestCasesToRun, IRunContext runContext, IFrameworkHandle frameworkHandle)

=== Pre-bind state information ===
LOG: DisplayName = EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/
LOG: Initial PrivatePath = NULL
Calling assembly : GoogleTestAdapter.TestAdapter, Version=0.9.1.653, Culture=neutral, PublicKeyToken=8d7bc984b03f1caf.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE/EnvDTE.EXE.

ERROR: 
================
The following errors and warnings occured during test execution (enable debug mode for more information):
ERROR: Couldn't find the msdia.dll to parse *.pdb files. You will not get any source locations for your tests.
Warning: Could not find source location for test aaa.bbb
ERROR: Exception while running tests: System.IO.FileNotFoundException: Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GoogleTestAdapter.TestAdapter.Framework.VsDebuggerAttacher..ctor(ILogger logger, Int32 processId)
   at GoogleTestAdapter.TestAdapter.TestExecutor.DoRunTests(IEnumerable`1 allTestCasesInExecutables, ICollection`1 testCasesToRun, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at GoogleTestAdapter.TestAdapter.TestExecutor.TryRunTests(IEnumerable`1 vsTestCasesToRun, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at GoogleTestAdapter.TestAdapter.TestExecutor.RunTests(IEnumerable`1 vsTestCasesToRun, IRunContext runContext, IFrameworkHandle frameworkHandle)

=== Pre-bind state information ===
LOG: DisplayName = EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/
LOG: Initial PrivatePath = NULL
Calling assembly : GoogleTestAdapter.TestAdapter, Version=0.9.1.653, Culture=neutral, PublicKeyToken=8d7bc984b03f1caf.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/EnvDTE/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES/MICROSOFT VISUAL STUDIO/2017/PROFESSIONAL/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/EnvDTE/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE/EnvDTE.DLL.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE.EXE.
LOG: Attempting download of new URL file:///C:/USERS/W7PRO/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_201CDE93/EXTENSIONS/TFMHQMQB.TUE/EnvDTE/EnvDTE.EXE.

========== Run test finished: 0 run (0:00:05.1933594) ==========

**Comment by csoltenborn** [comment]
@ninjaCoder Thanks for adding that information! You say that it started on March 14th - does that mean that source locations worked before that date on VS2017 even without having VS2015 installed?

@Farwaykorse Can you confirm the problems with debugging tests?

**Comment by Farwaykorse** [comment]
I do have both keys. Both are located in CLSID folders.  
**But** they point to non-existing locations of previous installs of VS.

 `e6756135-1e65-4d17-8576-610761398c3c` points to:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Packages\Debugger\msdia140.dll`  
`3bfcea48-620f-4b6b-81f7-b9af75454c7d` points to:
`C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Packages\Debugger\msdia120.dll`  

To make it more complex.  
The VS2017 install does contain the file. At:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Packages\Debugger\msdia140.dll`
So I did a search for register entries with `\msdia140.dll` in the `Data` field. This yielded only references to locations in the (almost) empty directories below `..\Microsoft Visual Studio 14.0\...`  
I found no reference in the registry to the VS2017 version of the file.  

By the way. The dll does work if I manually copy it to the referenced vs2015 location.

---
Debugging tests didn't ever produce unexpected errors for me.

**Comment by csoltenborn** [comment]
@Farwaykorse Thanks for the update - kind of as expected. It looks like VS2017 doesn't register the DIA DLLs publically any more... We'll look into this and figure out a reliable way to locate and instantiate the DIA DLL in case only VS2017 is installed - stay tuned.

@ninjaCoder It looks like your debugging problem is not related to this bug - would you mind to open a new issue and copy over your logging stuff? Thanks!

**Comment by Farwaykorse** [comment]
Maybe this can help: https://github.com/microsoft/vs-setup-samples

**Comment by csoltenborn** [comment]
Thanks! Your link might indeed be useful...

Until we have figured out a reliable way to instantiate the DIA com object on VS 2017, [this registry patch](https://github.com/csoltenborn/GoogleTestAdapter/files/908096/DiaRegistration.txt) should also provide a workaround without the need to copy dlls around. Change file ending to `.reg` and install - file locations should be found afterwards. The patch assumes the VS standard installation directory - adjust if needed.

**Comment by Farwaykorse** [comment]
Just confiming this registry patch is a working set (at least for the community edition of VS2017).

**Comment by jgefele** [comment]
[It's a documented breaking change in VS 2017.](https://docs.microsoft.com/en-us/visualstudio/extensibility/breaking-changes-2017#change-reduce-registry-impact)

**Comment by jgefele** [comment]
Hi @Farwaykorse,
would you please try [this build](https://ci.appveyor.com/api/buildjobs/3cwro7jdl0t8m641/artifacts/GoogleTestAdapter%2FVsPackage%2Fbin%2FRelease%2FGoogleTestAdapter-0.9.1.vsix)? It should fix your issues with DIA.

Cheers,
Jonas

**Comment by Farwaykorse** [comment]
@jgefele Perfect!

I removed the csoltenborn's temporary register patch, before installing.  
No errors and all the StackTrace links and references work again.

**Comment by bedder** [comment]
@jgefele I can also confirm that that build fixed issues I was having on VS2017 Enterprise. Cheers!
