### ISSUE TITLE
GTA with VS2017 and without linker option /DEBUG:FULL

### ISSUE THREAD

**Issue by Alfred5020** [csoltenborn/GoogleTestAdapter#127]
Hi!

Without the linker option /DEBUG:FULL GTA has a problem to discover the testlocation in the source and the code coverage doesn’t work well. Is something scheduled that it will also work with /DEBUG or /DEBUG:FASTLINK?

Regards
Alfred

**Comment by jgefele** [comment]
Hi Alfred,

first of all, please note that only your **tests** need to be compiled with /DEBUG:FULL. Your production code still can use /DEBUG:FASTLINK.

Our current implementation uses DIA (Microsoft's library for accessing PDB files) to enumerate all global symbols and find the test functions and their source line. [DIA doesn't support this for fastlink PDB](https://developercommunity.visualstudio.com/content/problem/4631/dia-sdk-still-doesnt-support-debugfastlink.html). In the linked bug report several other 3rd party tools reported similar issues. And I suspect your code coverage tool also faces this problem.

Unless Microsoft fixes this, there no way to fix our current way of getting source locations.

We thought about another idea to get source locations directly from the Google Test executable without DIA, however this would:
- require a complete rewrite of our method to get source locations
- only work with google test >= 1.8
- require you to compile google tests with some "listener" code provided by us

So it's unclear if we'll ever go this way. :(
