### ISSUE TITLE
Add support for $(ProjectName) VS "macro" in GTA Global Options "Working directory"

### ISSUE THREAD

**Issue by toussa** [csoltenborn/GoogleTestAdapter#128]
There are currently two placeholders possible in the "working directory" config entry (in Global Options: Tools/Options/GTA/General): 

- $(ExecutableDir): directory containing the test executable.
- $(SolutionDir): directory of the Solution (only available inside VS).

It could be really great if we can access to "$(ProjectName)" (Name of the Project).
Indeed, some tests can relie on resources available for specific projects, and then the working directory will depends on the Project name.

**Comment by csoltenborn** [comment]
Unfortunately, VS doesn't provide that information for us, and we do not know a reliable way to figure out that information given (only) the test executable. Thus, currently this is not possible - sorry for that...

**Comment by jgefele** [comment]
You can use the [`<ProjectSettings>` node in the configuration file](https://github.com/csoltenborn/GoogleTestAdapter#configuration) to set up different working directories for different test executables. Or see this [example](https://raw.githubusercontent.com/csoltenborn/GoogleTestAdapter/master/SampleTests/SampleTests.gta.runsettings).
