### ISSUE TITLE
Could not list test cases

### ISSUE THREAD

**Issue by lotfimira** [csoltenborn/GoogleTestAdapter#129]
Hi,

trying to use Google Test Adapter in Visual Studio 2012 Pro and got the following error:  -1073741515
Any idea what the problem is?
Thanks.

------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
Base.dll, Integrator.dll, Math.dll, Meshes.dll, ProfileAnalysis.dll, Surveys.dll, Tests.exe are built for Framework None and Platform X64.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
Google Test Adapter: Test discovery starting...
ERROR: Could not list test cases of executable 'E:\Dev\Insight\Insight1\x64\Debug\Tests.exe': executing process failed with return code -1073741515
Command executed: 'E:\Dev\Insight\Insight1\x64\Debug\Tests.exe --gtest_list_tests', working directory: 'E:\Dev\Insight\Insight1\x64\Debug'
Command produced no output
Found 0 tests in executable E:\Dev\Insight\Insight1\x64\Debug\Tests.exe
Test discovery completed, overall duration: 00:00:00.1988535
ERROR: 
================
The following errors and warnings occured during test discovery (enable debug mode for more information):
ERROR: Could not list test cases of executable 'E:\Dev\Insight\Insight1\x64\Debug\Tests.exe': executing process failed with return code -1073741515
Command executed: 'E:\Dev\Insight\Insight1\x64\Debug\Tests.exe --gtest_list_tests', working directory: 'E:\Dev\Insight\Insight1\x64\Debug'
Command produced no output
========== Discover test finished: 0 found (0:00:01.551141) ==========

**Comment by csoltenborn** [comment]
It appears that `Tests.exe` can not be executed for some reason. To figure out the cause, try the following: 

1. On the console, cd into `E:\Dev\Insight\Insight1\x64\Debug`.
2. Launch the command `Tests.exe --gtest_list_tests`

If your executable prints out the list of tests contained in that executable, we have a problem. Otherwise, the problem is yours ;-)

**Comment by jgefele** [comment]
Error code -1073741515 (0xc0000135) is STATUS_DLL_NOT_FOUND.

Note that by default the GoogleTestAdapter chooses "E:\Dev\Insight\Insight1\x64\Debug" as working directory. Does your Tests.exe expect another working directory to find all DLL-dependencies?

**Comment by csoltenborn** [comment]
Closed due to inactivity - feel free to re-open if you still have problems.

**Comment by Zuwei-Zhao** [comment]
My case of this error happening is because of lacking some dll files, including vcruntime.dll. Hope this information could help you.
