### ISSUE TITLE
If you group tests by project, typed tests with template argument are not linked with the correctly project. Instead they are in a project called external.

### ISSUE THREAD

**Issue by Alfred5020** [csoltenborn/GoogleTestAdapter#13]
Hi!
A small issue I have detecting if you group your tests by project and typed tests are used where the types parameter is a template.
If you modify the types parameter of the macro TYPED_TEST_CASE to be a non-template it will work.

The output of the test detection reports about they a warning:
Warning: Could not find source location for test CNetworkNetModuleCommand_fix/0.AktionAnstossen_NewCommand_HandlerCalled

Attached a file to reproduce the behavior.
[TypedTest2nd_test.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/76538/TypedTest2nd_test.txt)

**Comment by csoltenborn** [comment]
Hi Alfred,

thanks once more for your bug report, which allowed us to immediately reproduce the issue! You would make a great tester :-)

This time it was up to me to fix the bug - I've just pushed the updated source. As last time, you can download the fixed VSIX file from our CI server - here's the link:

https://ci.appveyor.com/api/buildjobs/wy22gl06w0il2hm1/artifacts/GoogleTestExtension/GoogleTestAdapterVSIX/bin/Release/GoogleTestAdapter-0.2.2.vsix

Note, however, that we will do an official release within the next couple of days. But if you still are in testing mood, go for it! :-)
