### ISSUE TITLE
stalled program run with --gtest_list_tests never recovers

### ISSUE THREAD

**Issue by pavelstudeny** [csoltenborn/GoogleTestAdapter#136]
It seems that GoogleTestAdapter finds tests by running executables in the Visual Studio output directory with a --gtest_list_tests.

When that program stalls/freezes/takes a long time to execute, e.g. when it ignores an unknown option such as --gtest_list_test, there is no recovery and the linker cannot write to those executables and the dlls they load anymore, until the process is killed by a task manager or so.

**Comment by jgefele** [comment]
Hello and thank you for your feedback.

We have added a timeout for test discovery here: "Cancel test discovery process after timeout" #90.
However, this improvement has not yet been released. You can either wait for the 0.10.0 to be released or try a [recent build of the development branch](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.9.1.747/job/lyuqtl8vtkdt57fa/artifacts).

You can also modify the [test executable regex](https://github.com/csoltenborn/GoogleTestAdapter#test_discovery_regex) to exclude certain executables from test discovery.

**Comment by pavelstudeny** [comment]
Thanks, i guess i can close this as a duplicate of #90. Until 0.10 gets released, the regex seems to be a feasible solution.
