### ISSUE TITLE
Installation of 0.10 nuget package is failing 

### ISSUE THREAD

**Issue by JackGrinningCat** [csoltenborn/GoogleTestAdapter#137]
Hi Team, 

I tried to update to your new version. Following error comes up from the installation.

> Could not install package 'GoogleTestAdapter 0.10.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**tltr:**
You need to have an native folder at least. 
`<file src="dummy.txt" target="lib\native\dummy.txt" />` or
~~`<file src="dummy.txt" target="content\native\dummy.txt" />`~~  (don't do this)

The nuspec was changed in this commit:
[NuspecFile](https://github.com/csoltenborn/GoogleTestAdapter/commit/5597df1022d6aa55b085cff1e65b7d801e217a73#diff-9b0038396808c7364e2d4dfe1ef72b99)

Nuget is using this lib folder to recognize "referenceable" libraries. This is totally aiming at the .NET environment. If a library framework is not available, they cannot reference it in the project type.

The native folder is basically the same, besides, it does no automatic references those libraries, because it cannot distinguish between all the binary flavors 🗡 ...
Therefore we have the freedom and responsibility to put just garbage in the lib or content folder allow it to be installed into a 'native,Version=v0.0' project.

Chris 

p.s. Don't put in the content folder ;) Actually it bind it in the project and that is always unwanted

**Comment by csoltenborn** [comment]
Chris, thanks a lot for your insightful bug report! We will release a fixed version soon.

Your approach seems to work fine with VS2017, but not VS2012 - I solved this by placing the MS  test framework DLLs into `lib\native`, but I would lie if I would claim that I understand what I'm doing here :-)

Since you seem to be pretty familiar with NuGet packaging, I have a follow-up question for you: If the adapter is installed via the VSIX file, we have our own options and a toolbar. Both is not available if installed via NuGet. I assume that this is a general problem - VS is not able to create our Package instance (see `GoogleTestExtensionOptionsPage` ) when installed this way. Is that correct, or are we doing something wrong, and that prevents VS from correctly creating our package instance?

**Comment by JackGrinningCat** [comment]
Hey Chris,

it is as you say. I followed up your request and tried to understand what is working and what not. 
But i cannot help your directly with your issue, but i can help me in my use-case

Ok, let's divide and conquer. 
My use-case:
Use nuget package to let any user of my repository have it's google test recognized by the vstest.console.exe.
When other users load it in Visual Studio it should find this *TestAdapter.dll. 

How could we solve the issue, that the vstest.console.exe is not finding the GoogleTest.TestAdapter.dll
As I understand, it searches all folder in it's path for *.TestAdapter.dll then use some reflexion and give it their context. Calls them when the user requests etc...

I tried to find good examples to use as it should. I was looking at the nunit.test adapter version changes of the nuget package. In the latest (stable) version, they just put everything in the tools folder. 
I did this with your package basically removing all stuff from lib and put it into the tools folder. 
I also deleted the build native folder, maybe that is needed for other purposes, but not for this.
![image](https://cloud.githubusercontent.com/assets/22233772/25747130/be7a1708-31a6-11e7-8417-29335f45d7a3.png)

Installed that package from a local folder, checked the package folder if nuget used the right one.
Then i deinstalled the extension on my visual studio. Restarted it and the solution, rebuild etc, after it started recognized the test within the test explorer. 

My use-case handled... everythings fine ... *jeah*
Divide-End

But i didn't find how nunit really makes the deal with extension options file or Toolbars or why in the newest alpha version of the nunit test adapter they don't use the tools folder. *argh* 
I older version they used install power scripts. *double argh*

To me, there is much documentation or clarity missing for me in the nuget world. It did change often in the beginning. I don't find any documented hint, why the tools folder is used by the vstest.console.exe. 

My five cents. 

Chris

p.s.
 - On the [nunit issues](https://github.com/nunit/nunit3-vs-adapter/issues/297) (scroll down about 1/3 of the discussion), there you can see, nunit people locking on mstest, xunit test adapter nuget specs to find out the best way to provide support for all the .NET frameworks. As this might not be your direct goal, you could maybe go with the tools folder.

p.p.s. I really tried to get a idea how to provide a way to get the extension options etc. through the nuget packet but i didn't find anything i could point on. Because i would not know what to look for [nuget API visual studio](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio)

**Comment by csoltenborn** [comment]
Ok, thanks for your investigation! I guess addindg a Package via a nuget development dependency is just not possible at the moment... I fixed this but (as mentioned above) by placing dlls in the `lib\native` folder - hope this works for all versions. If you want to give it a try, go for [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.10.0.779/job/uqc57wj5loly5xx7/artifacts)...

**Comment by JackGrinningCat** [comment]
Hi Christian,

I can install the version. 0.10.0. But it is not working.
The version 0.9.1 is working.

About the "my" TFS problems, i checked the build instructions and they didn't added the exe files for integration. So my bad. It was working all along.

**Comment by csoltenborn** [comment]
Sounds good!
