### ISSUE TITLE
Removed test cases will still be reported in the next run

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#139]
I remove some test cases. I do not explicitly rebuild (so that the test explorer does not refresh). Instead I directly rerun my last selection that still contains the removed test cases. I see warnings `Test adapter sent back a result for an unknown test case`.

I didn't debug or check if this is something new in 0.10 or pre-existing. My first guess is that it might be due to "Make use of already existing TestCase information to speed up execution of selected test cases" (#107). Maybe the test cases given to the test executor are a mixture of new/existing test cases updated during discovery and outdated/removed test cases coming from the user's selection. We would need to identify and discard the outdated ones.

Steps to reproduce:

In the sample project set `LoadTests` as test filter and then "run all tests":

```
------ Run test started ------
10:50:39.665 - Google Test Adapter: Test execution starting...
10:50:39.724 - Running 5000 tests...
10:51:12.931 - Google Test execution completed, overall duration: 00:00:33.2825478.
========== Run test finished: 5000 run (0:00:35,9609418) ==========
```

Now in `INSTANTIATE_TEST_CASE_P(, LoadTests, testing::Range(0, 5000));` change `5000` to `50` and do "repeat last run":

```
------ Discover test started ------
10:57:21.191 - Google Test Adapter: Test discovery starting...
10:57:21.376 - Found 50 tests in executable C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe
10:57:21.389 - Test discovery completed, overall duration: 00:00:00.1985270
========== Discover test finished: 50 found (0:00:00,9770644) ==========
------ Run test started ------
10:57:22.119 - Google Test Adapter: Test execution starting...
10:57:22.153 - Running 5000 tests...
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/100 [100]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1000 [1000]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1001 [1001]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1002 [1002]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1003 [1003]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1004 [1004]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1005 [1005]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1006 [1006]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1007 [1007]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1008 [1008]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1009 [1009]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/101 [101]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/1010 [1010]'.
...
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/997 [997]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/998 [998]'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'LoadTests.Test/999 [999]'.
========== Run test finished: 50 run (0:00:31,3812906) ==========
```

**Comment by csoltenborn** [comment]
Hm... here's what's happening:

* *Repeat last test run* triggers build of `LoadingTests.exe`
* Build triggers test discovery for `LoadingTests.exe`
* Adapter correctly reports that the executable contains 50 tests
* TestExecutor is triggered with 5000 tests
* We rely on them, run the executable and find 50 test results
* We report the other 4950 test results as *not run*
* VS complains

The behavior is different in the following scenario:

* Compile with `Range(0, 2)`
* Run test 1
* Change to `Range(0, 1)`
* *Repeat last test run*

Here, VS correctly reports that there are no tests to run. And another interesting one:

* Compile with `Range(0, 50)`
* Run all tests
* Change to `Range(100, 150)`
* *Repeat last test run*

VS runs the new (!) 50 tests because they have the same unique names as the old tests (but they are in fact different tests).

This is a VS bug in my opinion: VS ignores the update to `LoadingTests.exe` in some cases. Are they doing something like `testCasesToBeRun.Any(tc => availableTestCases.Contains(tc))`?

And it's hard for us to workaround, I guess:

* At test execution time, we do not know whether a test has no result because its executable has crashed, or because VS asks for runinng non-existent tests. Here's the only option I see: We could wait until the executable has finished, and report the test results only if there was a crashed test. That would however not cover the combination of test crashes and non-existing tests (they would still produce VS warnings).
* At the beginning of test execution, we can't decide whether tests exist without re-parsing the complete test executable, so there would be no point in re-using test cases.

However, the user will probably be aware that tests have just been removed, and that *Repeat last test run* probably wasn't the smartest choice made that day :-) Considering this, we are left with three options:

* Find out whether it's our fault that VS sends invalid test cases (e.g. because it is not able to match them) - I doubt that this is the case, but it wouldn't hurt to be absolutely sure
* Ignore the issue as a rare, easily understandable problem (and maybe document it)
* Get rid of reusing test cases

I think I'm with 2.

**Comment by jgefele** [comment]
Here another related issue:

* First run all on `Range(0, 10)`.
* Now repeat last run on `Range(0, 15)`

```
------ Discover test started ------
17:35:30.715 - Google Test Adapter: Test discovery starting...
17:35:30.805 - Found 15 tests in executable C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe
17:35:30.807 - Test discovery completed, overall duration: 00:00:00.0921403
========== Discover test finished: 15 found (0:00:00,6922725) ==========
------ Run test started ------
17:35:30.927 - Google Test Adapter: Test execution starting...
17:35:30.928 - Running 10 tests...
17:35:30.947 - >>>>>>>>>>>>>>> Output of command 'C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe --gtest_output="xml:C:\Users\Jonas\AppData\Local\Temp\tmpCD3C.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 -testdirectory=C:\Users\Jonas\AppData\Local\Temp\syxglcka.jij'
17:35:30.974 - [==========] Running 15 tests from 1 test case.
17:35:30.975 - [----------] Global test environment set-up.
17:35:30.976 - [----------] 15 tests from LoadTests
17:35:30.976 - [ RUN      ] LoadTests.Test/0
17:35:30.977 - [       OK ] LoadTests.Test/0 (0 ms)
17:35:30.977 - [ RUN      ] LoadTests.Test/1
17:35:30.978 - [       OK ] LoadTests.Test/1 (0 ms)
17:35:30.979 - [ RUN      ] LoadTests.Test/2
17:35:30.980 - [       OK ] LoadTests.Test/2 (0 ms)
17:35:30.980 - [ RUN      ] LoadTests.Test/3
17:35:30.981 - [       OK ] LoadTests.Test/3 (0 ms)
17:35:30.982 - [ RUN      ] LoadTests.Test/4
17:35:30.983 - [       OK ] LoadTests.Test/4 (0 ms)
17:35:30.984 - [ RUN      ] LoadTests.Test/5
17:35:30.984 - [       OK ] LoadTests.Test/5 (0 ms)
17:35:30.985 - [ RUN      ] LoadTests.Test/6
17:35:30.986 - [       OK ] LoadTests.Test/6 (0 ms)
17:35:30.987 - [ RUN      ] LoadTests.Test/7
17:35:30.987 - [       OK ] LoadTests.Test/7 (0 ms)
17:35:30.988 - [ RUN      ] LoadTests.Test/8
17:35:30.989 - [       OK ] LoadTests.Test/8 (0 ms)
17:35:30.990 - [ RUN      ] LoadTests.Test/9
17:35:30.990 - [       OK ] LoadTests.Test/9 (0 ms)
17:35:30.991 - ERROR: Failed to run test executable 'C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe': Sequence contains no matching element
17:35:30.992 - ERROR: Check out Google Test Adapter's trouble shooting section at https://github.com/csoltenborn/GoogleTestAdapter#trouble_shooting
17:35:30.993 - ERROR: In particular: launch command prompt, change into directory 'C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\', and execute the following command to make sure your tests can be run in general.
C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe --gtest_output="xml:C:\Users\Jonas\AppData\Local\Temp\tmpCD3C.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 -testdirectory=C:\Users\Jonas\AppData\Local\Temp\syxglcka.jij
17:35:32.014 - Google Test execution completed, overall duration: 00:00:01.0862194.
17:35:32.016 - ERROR: 
================
The following errors and warnings occured during test execution (enable debug mode for more information):
17:35:30.991 - ERROR: Failed to run test executable 'C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe': Sequence contains no matching element
17:35:30.992 - ERROR: Check out Google Test Adapter's trouble shooting section at https://github.com/csoltenborn/GoogleTestAdapter#trouble_shooting
17:35:30.993 - ERROR: In particular: launch command prompt, change into directory 'C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\', and execute the following command to make sure your tests can be run in general.
C:\Users\Jonas\Source\Repos\GoogleTestAdapter\SampleTests\Debug\LoadTests_gta.exe --gtest_output="xml:C:\Users\Jonas\AppData\Local\Temp\tmpCD3C.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 -testdirectory=C:\Users\Jonas\AppData\Local\Temp\syxglcka.jij
========== Run test finished: 10 run (0:00:01,1341557) ==========
```

Exception:
```
17:38:44.616 - ERROR: Stacktrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at GoogleTestAdapter.TestResults.StandardOutputTestResultParser.FindTestcase(String qualifiedTestname, IList`1 testCasesRun)
   at GoogleTestAdapter.TestResults.StreamingStandardOutputTestResultParser.ReportTestStart(String line)
   at GoogleTestAdapter.TestResults.StreamingStandardOutputTestResultParser.DoReportLine(String line)
   at GoogleTestAdapter.TestResults.StreamingStandardOutputTestResultParser.ReportLine(String line)
   at GoogleTestAdapter.Runners.SequentialTestRunner.<>c__DisplayClass15_0.<RunTestExecutableWithNewFramework>b__0(String line)
   at GoogleTestAdapter.Helpers.ProcessExecutor.NativeMethods.ExecuteCommandBlocking(String command, String parameters, String workingDir, String pathExtension, IDebuggerAttacher debuggerAttacher, Action`1 reportOutputLine, Action`1 reportProcessId)
   at GoogleTestAdapter.Helpers.ProcessExecutor.ExecuteCommandBlocking(String command, String parameters, String workingDir, String pathExtension, Action`1 reportOutputLine)
   at GoogleTestAdapter.Runners.SequentialTestRunner.RunTestExecutableWithNewFramework(String executable, String workingDir, Args arguments, IProcessExecutor executor, StreamingStandardOutputTestResultParser streamingParser)
   at GoogleTestAdapter.Runners.SequentialTestRunner.TryRunTests(String executable, String workingDir, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher, Args arguments, String resultXmlFile, IProcessExecutor executor, StreamingStandardOutputTestResultParser streamingParser)
   at GoogleTestAdapter.Runners.SequentialTestRunner.RunTests(String executable, String workingDir, Boolean isBeingDebugged, IDebuggedProcessLauncher debuggedLauncher, Args arguments, String resultXmlFile, IProcessExecutor executor, StreamingStandardOutputTestResultParser streamingParser)
```

This indicates we're not getting a "a mixture of new/existing test cases updated during discovery and outdated/removed test cases coming from the user's selection" as I speculated before. Instead we just get the "outdated test cases coming from the user's selection". These tell us to run 10 (of 10) tests in the suite. We run the whole suite and get caught unprepared when the 11th test case finishes... :(

The crash can of cause be fixed with a SingleOrDefault, blabla. But it's still not nice to run more than we are told. OTOH it would be sad to revert #107 just because of this...



BTW: Your finding on `Range(0, 50)` change to `Range(100, 150)` needs a little thought, too. For numbers you might say "so what". But what if you get different *interfaces* in a (non-value-)parameterized test change, because you add/remove an interface? But of course this is an unrelated issue.

**Comment by csoltenborn** [comment]
be886d6 is supposed to do the following:
* If VS asks us to run test cases which do no longer exist, we recognize this as long as the executable doesn't crash. We ignore these test cases and produce a warning in debug mode
* Test results for which we [do not have a test case](https://github.com/csoltenborn/GoogleTestAdapter/issues/139#issuecomment-299649256) are also ignored and produce a warning in debug mode - note that the according tests are executed

**Comment by jgefele** [comment]
[![LGTM](http://lgtm.in/p/8OVYoSSTp)](http://lgtm.in/i/8OVYoSSTp)
