### ISSUE TITLE
v 0.10.1 nuget package not working on vs2015

### ISSUE THREAD

**Issue by JackGrinningCat** [csoltenborn/GoogleTestAdapter#142]
Hi Chris,

I tried the new nuget version you send me a link. I can install it but it's not working
0.9.1 is working.  The 0.10.0 visual studio extension is also working.

This is the only output on my "Tests" log in Visual Studio:
```
C:\Users\JackGrinningCat\AppData\Local\Temp\VisualStudioTestExplorerExtensions\GoogleTestAdapter.0.10.0/lib/net45/GoogleTestAdapter.TestAdapter.dll
------ Load Playlist started ------
========== Load Playlist finished (0:00:00,0035033) ==========
------ Discover test started ------
NUnit Adapter 3.7.0.0: Test discovery starting
<Snip-Snap>
NUnit Adapter 3.7.0.0: Test discovery complete
========== Discover test finished: 70 found (0:00:01,7852402) ==========
```

Can you help me to get more meaningfully output from Visual Studio.

**Comment by csoltenborn** [comment]
What exact version of VS2015 is this? I have [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.10.0.781/job/g5j1r5cb6duj7ayk/artifacts) (no changes relevant to NuGet) running on VS2015 Community V14.0.25431.01 (update 1) without any problems...

One side note: I've seen "refresh issues" with NuGet installations of GTA. If I want to make sure that I'm starting on a rather clean environment, I delete not only `SampleTests/packages`, but also all files within folder `%appdata%/..` which contain `GoogleTestAdapter` (skip files which can not be deleted).

**Comment by JackGrinningCat** [comment]
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Professional



LightSwitch for Visual Studio 2015   00325-60000-26132-AA050
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00325-60000-26132-AA050
Microsoft Visual Basic 2015

Visual C# 2015   00325-60000-26132-AA050
Microsoft Visual C# 2015

Visual C++ 2015   00325-60000-26132-AA050
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00325-60000-26132-AA050
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.19.00411.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Child Process Debugging Power Tool   1.0
Power tool to add child process debugging to Visual Studio.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Tools   1.10.188
Contains numerous tools and helpers that makes it easier than ever to build Visual Studio extensions.

Google Test Adapter   1.0
Google Test Adapter adds support for the C++ test framework Google Test

Intel® Advisor 2017 Update 2   
Intel® Advisor 2017 Update 2, (build 501009), Copyright © 2009-2016 Intel Corporation. All rights reserved.

Intel® Inspector 2017 Update 2   
Intel® Inspector 2017 Update 2, (build 497970), Copyright © 2009-2016 Intel Corporation. All rights reserved.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2017.1.1    Build 108.0.20170407.122957
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

OpenCppCoverage   1.0
See https://opencppcoverage.codeplex.com/ for more details

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
https://GitHub.com/EWSoftware/SHFB

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by JackGrinningCat** [comment]
It did work.

I deleted the the appdata and after and restart it worked. Holy moly! After some days, I can update it on the tfs :)

Btw. thanks for your effort.

**Comment by csoltenborn** [comment]
You're welcome ;-) - glad to hear that it works now!
