### ISSUE TITLE
Could not parse duration with ','

### ISSUE THREAD

**Issue by cbsuh** [csoltenborn/GoogleTestAdapter#143]
version: 0.10.0.777

`[       OK ] Redis.ConnectDockerizedServer (4,656 ms)`
`Warning: Could not parse duration in line '[       OK ] Redis.ConnectDockerizedServer (4,656 ms)'`

I guess that the cause is ',' among duration.

**Comment by csoltenborn** [comment]
Thanks for your report! Weird - we haven't seen such values up to now. Two questions:
* How long does this test take? Is it 4656ms (=4.656s) or 4.656ms?
* What is your build environment? This is just out of curiosity - we'd like to know where that value comes from...

We are going to release version 0.10.1 pretty soon - if you answer within the next couple of hours, the fix for this will go into that version.

**Comment by jgefele** [comment]
internally in google test time is just a 64-bit integer: `typedef TypeWithSize<8>::Int TimeInMillis;  // Represents time in milliseconds.`

`PrettyUnitTestResultPrinter::OnTestCaseEnd` just `printf`s a string it's gotten from `internal::StreamableToString(test_case.elapsed_time())`

`StreamableToString` streams this integer into class `Message` which streams it into `std::stringstream`.

The output will always be an integer, no decimals.

So what @cbsuh sees is the number fourthousandsixhundredfiftysix in the current locale, i.e. with comma as thousands separator.

**Comment by jgefele** [comment]
Okay... I cannot commit a fix because somebody used C# features which won't compile in my VS2015... :cry:

I suggest the following fix
```
                // duration is a 64-bit number (no decimals) in the user's locale
                int indexOfOpeningBracket = line.LastIndexOf('(');
                int lengthOfDurationPart = line.Length - indexOfOpeningBracket - 2;
                string durationPart = line.Substring(indexOfOpeningBracket + 1, lengthOfDurationPart);
                durationPart = durationPart.Replace("ms", "").Trim();
                durationInMs = int.Parse(durationPart, NumberStyles.Number);
```

Changed:  the comment and `NumberStyles.Number` in the last line.
