### ISSUE TITLE
Test Adapter for Google Test by Microsoft doesn't work with latest Visual Studio 2017 update 

### ISSUE THREAD

**Issue by grandtiger** [csoltenborn/GoogleTestAdapter#146]
I tried to use the version published by Microsoft (v0.9.1), but I am not able to create a Google Test project following this page: https://blogs.msdn.microsoft.com/vcblog/2017/05/10/unit-testing-and-the-future-announcing-the-test-adapter-for-google-test/

The version of Visual Studio 2017 is the latest update Version 15.2 (26430.14). I happened to have another PC that is on an older version 15.2 (26430.6), and I can create a Google Test project using that older version.

Could someone look into this and fix the compatibility issue? Thanks a lot!

BTW, the error is "Creating project 'xxxx-Test1' ... project creation failed.

**Comment by csoltenborn** [comment]
Thanks for your bug report! However, maintenance for the MS version of our adapter is out of our scope, especially since the project templates have not made it back to our code (yet). Thus, please file an issue at [this repository](https://github.com/Microsoft/TestAdapterForGoogleTest)
