### ISSUE TITLE
Specify additional PDB for source location

### ISSUE THREAD

**Issue by sephirostoy** [csoltenborn/GoogleTestAdapter#153]
Hello,

I'm facing an "Warning: Could not find source location for test ..." issue; but I think it comes from my particular setup.
I have an executable acting only as a main launcher: it loads dynamically some dlls which contains the google tests, like so:

> ./LauncherTest.exe
> ./addonsTest/Library1Test.dll
> ./addonsTest/Library2Test.dll

These dlls generate their own PDB containing source location information. But I guess that GTA is only looking at the exexutable's PDB which here doesn't contain any useful information, right?

If so, is it possible to specify additional PDB files to look for the needed information? A regex would be nice.

Note that except this issue, I can run & debug the tests smoothly.

Thanks,
Tony

**Comment by csoltenborn** [comment]
Have you tried to enable debugging? This should tell you all locations the adapter looked at while searching for your PDBs... this might give you a better idea on what's going on. In fact, GTA is extracting the imports from the given executable and looks for their pdbs, too, but this happens only in the test executable's directory if I remember correctly, so it wouldn't help here.

However, there already is an option to specify additional locations: Try to add your `addonsTest` directory to the *PATH extension* option of GTA. That option usually takes care of different problems, but might help you, too :-)

Let me know whether any of this helps!

**Comment by sephirostoy** [comment]
I've tried to add the folder to the PATH extension by either relative path from $(ExecutableDir) or using absolute path, it doesn't fix it.
When I activate the debug print, I see that it's loading the PDB of the executable plus the PDBs of the few dlls the executable depends on (they are on the executable directory); but not the PDBs for the test dlls (their PDB are also in the addonsTest folder).
Note also that there are other PDBs present in executable directory but they are not loaded too.

So I guess that it's loading only the PDBs for the executable plus its dependencies.
In my case, the test dlls are loaded dynamically, it's not the executable which depends on them.

Hope it helps.

**Comment by csoltenborn** [comment]
Now I've understood the meaning of *loading dynamically* :-) There's currently no way to deal with such setups. I've tagged this *enhancement*, but it will take us some time because we are currently waiting to merge quite a bit of code into our repository.

**Comment by sephirostoy** [comment]
Thanks for considering this as enhancement.
Actually it's not a big problem since once the tests ran, and if they failed, the stacktrace - in the Test Explorer window - provides links to go to the source where the test failed.

Btw, congrats for your partnership with Microsoft to make this addin even greater :)

**Comment by csoltenborn** [comment]
You're welcome, and thanks :-)

**Comment by csoltenborn** [comment]
@sephirostoy [This build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.1.975/artifacts) contains an option to specify additional PDB files - would you mind to give it a try?

**Comment by sephirostoy** [comment]
@csoltenborn I've tested this build and it's working if I specify the path to the PDB file:
`$(ExecutableDir)/addonsTest/myLibraryTest.pdb`
Then "Test Explorer" display the file and the line containing the test, and if I double click on a test, it jumps to it. Nice!
I'm wondering if it's possible to define a regex to search for PDBs instead of enumerating each one. I've tried something like:
`$(ExecutableDir)/addonsTest/.*Test\.pdb`
but it didn't worked. Is it possible with this build or not yet implemented?

Finally, I've tested in VS 2017 15.3.2 => working
and also VS 2017 15.5.0 Preview 4 => Test Explorer is crashing with this new build: instead of having the normal test explorer interface, I have a plain text error message (see attached).
[test_explorer.log](https://github.com/csoltenborn/GoogleTestAdapter/files/1485075/test_explorer.log)

**Comment by csoltenborn** [comment]
Thanks for your feedback!

I thought about providing a regular expression (I had seen your according comment), but decided not to because I didn't want to match all files under the working dir (and that's probably what I would have to do), so I fear that you are stuck with adressing them each one. I hope that's fine for you - keep in mind that it's a one-time effort :-) Note also that by making use of project settings, you can provide PDBs specific to each test executable, and you can share them (with your team) by means of a solution settings file.

**Comment by sephirostoy** [comment]
I understand even if sometimes it would makes sense. In my case, "addonsTest" subdirectory contains only google tests DLLs and their PDBs, and they all end with "Test.dll". Currently there are up to 20 test projects and it's growing regularly.
The same goes with the executable regex: by default you provide a regex pointing on every executable ending with "Test.exe" ; I had one case where an executable ending with "Test.exe" was not a google test project, and GTA did launch it accidentally during discovery phase. So the regex was useful here to avoid it.
I think the regex it's the best compromise to let the final decision to the user.

**Comment by csoltenborn** [comment]
Ok, I guess I'm convinced ;-)

Give me a couple of days...

**Comment by csoltenborn** [comment]
I have finally added support for wildcards (which can be used in the file part - I basically split path and file part and then invoke [this API](https://msdn.microsoft.com/de-de/library/wz42302f(v=vs.110).aspx)). If you want to give it a try, please use [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.3.1006/artifacts).

**Comment by sephirostoy** [comment]
It sounds to work on VS 2017 15.3.2. I changed the string to:
`$(ExecutableDir)/addonsTest/*Test.pdb`
So Test Explorer finds the source for all my tests, whatever the project.

However, I've tried also with the current preview 15.6 update 3 and the additional PDBs feature does not work anymore, even if I list one by one the files and even if I give their absolute path.

**Comment by csoltenborn** [comment]
Thanks for testing! I have not played with that version of VS, I must admit - let's hope that MS hasn't (again) broken something (e.g., GTA doesn't work with `VsTest.Console.exe` any more since V15.5)... Do the other settings have any effect with the preview version of VS?

**Comment by sephirostoy** [comment]
I don't think the other settings are affected. At least, I only use few of them.
If you look at the release note of v15.6 update 2:
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes
> The Test Explorer now has a hierarchy view and real time test discovery is on by default.
This might affect your discovery.

**Comment by csoltenborn** [comment]
Thanks for the link... real time test discovery is enabled for managed languages only, it appears (needs Roslyn). I'm not at all sure what the hierarchical view will mean for GTA...

Can you please double-check whether the other options indeed do work? I do not see any reason why the new option should not work, but others should... Maybe you can just enable/disable debug mode and have a look at the produced output...

**Comment by sephirostoy** [comment]
The other options are working, especially the custom regex to match the executable: when debut prints are activated:
[12/02/2018 14:00:58 Informational] Custom regex 'MyTests.exe' matches executable 'E:\Sources\master\exe\Debug_x64\MyTests.exe'
However, there's no log regarding the PDBs location failure. In the log there's only the enumeration of all settings:
[12/02/2018 14:00:58 Informational] Solution settings: AdditionalPdbs: 'E:/Sources/master/exe/Debug_x64/addonsTest/MyLibraryTest.pdb', AdditionalTestExecutionParam: ''...

**Comment by csoltenborn** [comment]
Sorry for only coming back to you now...

I've added some debug output (GTA will warn the the pattern does not match any files, and will in debug mode print out the number of files matched by the pattern). If you want to give it another try, please use [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.3.1013/artifacts).

I also updated the description of the *Additional PDBs* option - feel free to provide feedback!

**Comment by sephirostoy** [comment]
Well, mea culpa.
I've just realized now that in my VS 2017 Preview "Parse symbol info" was turned OFF; wheras it was turned ON in my VS 2017 Release; that's why it didn't even try to look for symbols... -____-. Turning on solved the problem.
I was so focus on "Additional PDBs" field so I didn't look at "Parse symbol information". Maybe the 2 fields should be side by side since they are related?
In any case, the feature is OK for me.

**Comment by csoltenborn** [comment]
Ok, I see... To increase your pain: This is part of the "no source location" trouble shooting section ;-)

I don't think that I can influence the order of the settings (despite grouping them)...
