### ISSUE TITLE
Failed to detect any unit test for large test project

### ISSUE THREAD

**Issue by burbelgruff** [csoltenborn/GoogleTestAdapter#158]
https://github.com/csoltenborn/GoogleTestAdapter/blob/fd10b8110bf0f057ed73463223412502b1925272/GoogleTestAdapter/DiaResolver/PeParser.cs#L170

The problem appears when pdbPath is null for one of the nested dlls of the test project. 
The following code solves the problem:
`if (dbgDir != null && dbgDir->SizeOfData > 0)`

**Comment by csoltenborn** [comment]
Thanks for your bug report! In fact, this issue showed up already as part of #150. Thanks anyways - will be fixed with the next version.
