### ISSUE TITLE
ERROR: Could not list test cases of executable (VS2017 15.3.2, x64 test)

### ISSUE THREAD

**Issue by Veroni23** [csoltenborn/GoogleTestAdapter#159]
Hi, 

I am using VS2017 15.3.2 on Windows 10. My builds are x64 builds in Debug and Release configuration.

During test discovery in Release configuration, I get this output (I changed the names of the libraries...):

`[24-Aug-17 9:14:20 Informational] ------ Discover test started ------`
`[24-Aug-17 9:14:20 Warning] Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
foo.lib, bar.lib, baz.lib, tests.exe are built for Framework None and Platform X64.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.`
`[24-Aug-17 9:14:20 Informational] Test Adapter for Google Test: Test discovery starting...`
`[24-Aug-17 9:14:21 Error] ERROR: Could not list test cases of executable 'C:\Projects\nupf-ioutils\build\bin\foo\win32-x86_64-vc141\Release\tests.exe': executing process failed with return code -1073741701
Command executed: 'C:\Projects\foo\build\bin\foo\win32-x86_64-vc141\Release\tests.exe --gtest_list_tests', working directory: 'C:\Projects\foo\build\bin\foo\win32-x86_64-vc141\Release'
Command produced no output`
`[24-Aug-17 9:14:21 Informational] Found 0 tests in executable C:\Projects\foo\build\bin\foo\win32-x86_64-vc141\Release\tests.exe`
`[24-Aug-17 9:14:21 Informational] Test discovery completed, overall duration: 00:00:00.3991158`
`[24-Aug-17 9:14:21 Error] ERROR: `

The discovery works fine in Debug configuration. I am using gtest in a standard way - no extra parameters. Calling ./tests.exe --gtest_list_tests from the working directory specified above works fine in the cygwin console, but calling it in the windows command prompt raises a dialog with error code 0xc000007b. This also happens on Windows 7.

Notice the warning in the test adapter output about the platform? The link in the message describes how to set the test architecture. When I set the test architecture to x64 as described there, the warning disappears, but the behavior is the same (except for the warning).

Is this a bug or am I missing some configuration for google test adapter?

**Comment by csoltenborn** [comment]
If the tests cannot be listed on the console, GTA doesn't have any chance to discover tests, because that's what the adapter is doing. Since you can list your tests on th CygWin console, there apparently is a difference between the two execution environments - that's where you should look in my opinion.

If it turns out that there's something on the `PATH` that's missing at the Windows console (that would in fact be my guess), you can use GTA's *Path extension* option to add that stuff to the path.

Hope this helps - let me know whether it did!

**Comment by Veroni23** [comment]
Thanks for the clarification. At this point I have no idea what to change in the environment. The PATH is identical between the cygwin and the windows console except for additional /usr/local/bin and /usr/bin in cygwin.

**Comment by Veroni23** [comment]
This can be closed: The reason was a missing DLL. When it is copied into the Release/ directory, the executable starts both in the windows console and in VS2017. 

Sorry to bother you. I wish error messages for DLLs would be clearer on Windows... :(

**Comment by csoltenborn** [comment]
No problem at all - glad that it works for you now.
