### ISSUE TITLE
Run tests after build does not work

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#16]
**Symptoms**: Selecting the Run tests after build option does not or not always result in the tests being run after build completion. Instead, the following error message is printed to the test console: "The specified type member 'Stale' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported."

**Reason**: We have no idea

**Workaround**: None so far

**Comment by LukaszMendakiewicz** [comment]
Is this still an issue in latest versions of the adapter and Visual Studio? I was not able to reproduce the problem in a few quick attempts.

**Comment by csoltenborn** [comment]
I will check this out and let you know!

**Comment by csoltenborn** [comment]
This indeed seems to have been fixed (maybe even a while ago) - at least I can not reproduce it with VS 15.9.4.
