### ISSUE TITLE
Failed build on GTest for a Shared project due to pch.cpp

### ISSUE THREAD

**Issue by hilllo** [csoltenborn/GoogleTestAdapter#162]
Hello, I was creating a **GTest** project for a **Shared** project in Visual Studio. The **Shared** project contains a `pch.cpp` file, while the **GTest** project created by default also contains a `pch.cpp` file. There are some errors I got while trying to build the **GTest** project:

- When I try to build it, I got  `test.cpp(4): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int` , `test.cpp(4): error C2448: 'TEST': function-style initializer appears to be a function definition` and so on.  
    - So I removed the References of the Shared project, commented the code which is related to the Shared project, and built it successfully. 
    - Then, I added the Shared project back as references, uncommented the codes, built it and succeeded, which is weird cause I didn't change anything.

- I also got the warning as `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(937,5): warning MSB8027: Two or more files with the name of pch.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are C:\Users\...\Shared\pch.cpp, pch.cpp.`. Seems like there are conflicts between the 2 `pch.cpp` files in the **GTest** project and the **Shared** project. But if I deleted the `pch.cpp` file of the **GTest** project, which is redundant, the build would fail again.

**Comment by csoltenborn** [comment]
I fear this is out of scope of GTA, which comes into play as soon as a test executable is successfully built, but does not affect the build itself...

Feel free to re-open if you do not agree.
