### ISSUE TITLE
Grouping by Project Displays All Google Tests as "External" in Visual Studio 2017 When Build with the v141 Toolset

### ISSUE THREAD

**Issue by ChristopherTheunissen** [csoltenborn/GoogleTestAdapter#163]
Test Explorer groups all Google Tests under "External" when grouping by Project.

I am using:
Visual Studio 2017 (15.3.3)
Google Test Adapter 0.10.2.874

This is different to issue #13, as I am not using TYPED_TEST_CASE.

**Comment by ChristopherTheunissen** [comment]
This seems to be an issue with projects built with the Visual Studio 2017 (v141) toolset, as it correctly displays the projects in Visual Studio 2017 when they are built using 2013 (v120) and 2015 (v140) toolsets.

**Comment by csoltenborn** [comment]
I can not reproduce this: our sample solution is built against the v141 toolset when opened with VS2017 and does not have this problem.

Can you attach a (preferable minimal) example solution?

**Comment by ChristopherTheunissen** [comment]
I don't know if it makes a difference, but they were Visual Studio 2013 (v120) projects upgraded to 2017 (v141) targeting Windows SDK 8.1.

I can't provide an example at the moment, as I have to get on with development targeting 2015 (v140), as third party support for v141 is not stable enough yet.

I will post again when I  Port another project in the next few weeks.

________________________________

**Comment by csoltenborn** [comment]
Ok, sounds good to me - looking forward to your example solution!

**Comment by csoltenborn** [comment]
I'm closing this issue for now - feel free to reopen if the problem remains!
