### ISSUE TITLE
Error discovering tests

### ISSUE THREAD

**Issue by angocor** [csoltenborn/GoogleTestAdapter#164]
Hello.

I am getting the following error when I compile my test project in VS2013 with Google Test Adapter.

------ Discover test started ------
Google Test Adapter: Test discovery starting...
ERROR: Could not list test cases of executable 'D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug\HDCpuITests.exe': executing process failed with return code -1073741502
Command executed: 'D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug\HDCpuITests.exe --gtest_list_tests', working directory: 'D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug'
Command produced no output
Found 0 tests in executable D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug\HDCpuITests.exe
Test discovery completed, overall duration: 00:00:01.4000524
ERROR: 
================
The following errors and warnings occured during test discovery (enable debug mode for more information):
ERROR: Could not list test cases of executable 'D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug\HDCpuITests.exe': executing process failed with return code -1073741502
Command executed: 'D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug\HDCpuITests.exe --gtest_list_tests', working directory: 'D:\Users\agonzalez\git\next32\Libraries\HDCpuI\HDCpuITests\Debug'
Command produced no output
========== Discover test finished: 0 found (0:00:01.6427773) ==========

Any idea of what this error means?. What is the return error code -1073741502?. I noticed this error happens when I try to link a DLL I need for my tests, however since I don't know what the return error is I feel clueless of why adding the DLL affects the test discovery.

**Comment by csoltenborn** [comment]
Have you checked out our trouble shooting guide? Make sure that test discovery can be run from console. Let me know if this does not help...

**Comment by csoltenborn** [comment]
Closed due to inactivity - feel free to reopen if you still have problems.
