### ISSUE TITLE
Tests to run always specified on command line, even if running all tests in executable

### ISSUE THREAD

**Issue by DominikGrabiec** [csoltenborn/GoogleTestAdapter#18]
The bug is that all of the tests suites are specified in the filter on the command line if the whole project is run or even run all is selected. 

This occurs because there is a bug in the CommandLineGenerator.AllTestCasesOfExecutableAreRun function. It assumes that the AllTestCases variable only contains tests for that executable, but it actually contains all of the tests for all executables to be run.

To reproduce:
 * Make a solution with two test executable projects and add tests to both.
 * Put a breakpoint in one of the tests
 * In Test Explorer select the project view and right click on one project and "Debug Selected Tests" or even "Debug All".
 * When the breakpoint is hit, check Process Explorer for the test executable and examine the command line parameters.

If running all the tests in an executable there should be no command line parameters.

**Comment by csoltenborn** [comment]
Thanks for your excellent bug report. However, I think the assumption in CommandLineGenerator should be fine - I decided to select the test cases for the according executable already in SequentialTestRunner, which should fix the issue, too, and additionally be more consistent with what shall actually happen.
