### ISSUE TITLE
[Question] How do I get test discovery for custom executable (executable in another directory)

### ISSUE THREAD

**Issue by Dark-Passenger** [csoltenborn/GoogleTestAdapter#187]
For our project the executable is moved into a custom directory and its usable only in that directory. How do I configure gtest Adaptor to run the custom executable rather than the default output.

**Comment by csoltenborn** [comment]
Unfortunately, this is not possible. The reason is that the test executables to be run are delivered to GTA by the VS test framework - I do not have any influence on that one...
