### ISSUE TITLE
Working directory is not correct

### ISSUE THREAD

**Issue by harrynull** [csoltenborn/GoogleTestAdapter#188]
It says:
```
Command executed: 'D:\Projects\SomeProject\build\Debug\test.exe --gtest_list_tests', working directory: 'D:\Projects\SomeProject\build\Debug'
```
However, the working directory is not really what it says. Instead, it becomes `D:\Softwares\Visual Studio 15\Common7\IDE` and `D:\Softwares\Visual Studio 15\Common7\IDE\CommonExtensions\Microsoft\TestWindow`, where `D:\Softwares\Visual Studio 15\` is where Visual Studio is installed. (depends on if it is listing tests or executing tests)

**Comment by csoltenborn** [comment]
Thanks for letting me know - what exact VS version is this? My first guess is that this is another regression...

**Comment by harrynull** [comment]
Visual Studio version is 15.4.5 (Community 2017)

**Comment by csoltenborn** [comment]
Ok, that's the exact same version I'm currently running, and I can confirm that this is indeed the case. As a workaround, you can use the `WorkingDir` option with value `$(ExecutableDir)`. I will try to figure out if this is indeed a regression, but this will probably take a few days...

**Comment by harrynull** [comment]
Could you tell me how to set `WorkingDir` option? The WorkingDir option in Tools/Options/Google Test Adapter defaults to $(ExecutableDir) and changing that does not seem to work.

**Comment by csoltenborn** [comment]
Please see the documentation on settings (don't have time right now to explain)... Hint: If you enable debug output, you will see what settings are actually used for your test projects.

**Comment by csoltenborn** [comment]
Have you been able to figure out the settings issue?

**Comment by harrynull** [comment]
Nope, I still could not set the working directory correctly.

**Comment by csoltenborn** [comment]
Ok, then I need some more info, e.g. your log output after enabling Debug mode, whether you have configured a solution settings file or a test settings file (I assume you have read the docs) - "still doesn't work" isn't exactly helpful ;-)

**Comment by harrynull** [comment]
I tried it again and it somehow works now. Thank you for your help.

**Comment by csoltenborn** [comment]
Good to hear, and: you're welcome!

**Comment by pifopi** [comment]
Hey ! It seems that I have the same issue. I tried to put the working dir as $(ExecutableDir) as well as the absolute path of the directory but it's still not working.

It is saying that in the ouput :
[13/02/2018 11:26:19 Error] 11:26:19.223 - ERROR: Test discovery was cancelled after 30s for executable D:\Perforce\bin\win64\functionaltestspeer_d.exe
[13/02/2018 11:26:19 Error] 11:26:19.224 - ERROR: Test whether the following commands can be executed sucessfully on the command line (make sure all required binaries are on the PATH):
cd "D:\Perforce\bin\win64"
functionaltestspeer_d.exe --gtest_list_tests

I tried that but it's not working either (visual studio 2017 is installed on my C drive and my project must be on my D drive). Do you know if I could force the "/D" to change the current drive?

PS : I have the version 15.4.0

Thanks in advance !

**Comment by csoltenborn** [comment]
I will release a fix for this in the next, say, two weeks. In fact, `$(ExecutableDir)` should work just fine during test execution (fix makes sure that the directory of the excutable is also used if option is empty); however, during test discovery it is completely ignored (fix will change this).

**Comment by csoltenborn** [comment]
Would you mind to give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.3.1015/artifacts) a try, which contains the fixes mentioned above?

**Comment by pifopi** [comment]
I will try this version on Monday. Unfortunately, I don't have my computer this weekend.
Thanks you very much for your time and for this amazing tool :)

**Comment by pifopi** [comment]
Everything works fine with your fix ;)
Thanks you for this fix !

**Comment by csoltenborn** [comment]
Thanks for testing!
