### ISSUE TITLE
Incorrect shortcutting for parametrized tests on the results list

### ISSUE THREAD

**Issue by michalfita** [csoltenborn/GoogleTestAdapter#190]
First, thank you for great plugin! It really helps a lot.

I recently started using parametrized tests of Google Tests framework as described in [this tutorial](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#how-to-write-value-parameterized-tests). But the list of results in the plugin's pane incorrectly handles shortcutting names, it put three dots after the slash character, which separates instantiation name from the test name.

Picture worth thousand words:
![paneshot](https://user-images.githubusercontent.com/4925040/34830050-979777da-f6da-11e7-9129-a3b9c96b899f.png)

As you see, long test names are cut at the edge; instantiated tests names that fit are displayed complete; remaining are cut too early.

**Comment by csoltenborn** [comment]
Thanks for your kind words!

I fear your problem is out of scope of GTA - the wrapping of test names is performed by VS. However, I think that I have you covered already (see #23): Please use option *Test name separator* - let me know whether this helps!

**Comment by michalfita** [comment]
What a shame (on M$ of course 😄 )... Thanks, it works!

**Comment by csoltenborn** [comment]
Sweet ;-)
