### ISSUE TITLE
CommandLineGenerator.GetFinalCommandLines() fails to support very large sets of test-suites

### ISSUE THREAD

**Issue by MartinOSchmidt** [csoltenborn/GoogleTestAdapter#192]
Dear Christian,
if one has a very large number of test-suites in a test.exe (e.g. hundreds or thousands of suites), and tries to use trait-filters, chances are high that CommandLineGenerator.GetFinalCommandLines() fails to work properly due to the code line

>  int remainingLength = MaxCommandLength
>                 - baseCommandLineWithFilter.Length - _lengthOfExecutableString - userParam.Length - 1;

where _remainingLength_ may become negative.
Find attached a patch-file (only the changes to CommandLineGenerator.cs are of interest) to fix this problem by modifying the used approach.
Would be great if the changes could be incorporated into the master/trunk.

Feel free to ask anything with respect to my changes.

Cheers

Martin
[0002-bugfix-GetFinalCommandLines-string-baseCommandLine-n.zip](https://github.com/csoltenborn/GoogleTestAdapter/files/1656218/0002-bugfix-GetFinalCommandLines-string-baseCommandLine-n.zip)

**Comment by csoltenborn** [comment]
Thanks a lot for the patch! Would you mind opening a pull request against master for it? We would then benefit from CI, code review is much easier, plus your commit(s) will end up in GTA's history :-)

**Comment by MartinOSchmidt** [comment]
Sorry, I am very new to github, Christian. I first wanted to create a "pull request", but was puzzled about how to do it, so I added the issue. Do I need to create a new branch first, to be able to to this. Do I need to install the Github-Application for this?

**Comment by csoltenborn** [comment]
No problem! You basically need to push your change into your clone of my repository (into it's own branch) - then, you can create pull request via the GitHub web interface against my master branch. [Here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)'s some more info... It looks complicated at first glance, but in fact isn't (but amazingly powerful).

**Comment by MartinOSchmidt** [comment]
Great. Finally managed to do the pull-request :) - to "create a fork" was the missing puzzle-piece ...
