### ISSUE TITLE
Wrong Sorting of Parametric Testcases

### ISSUE THREAD

**Issue by gobater** [csoltenborn/GoogleTestAdapter#197]
Hi,

If've found a "minor" issue with the Adapter.
For Parametric tests (TEST_P), the adapter is not showing the testcases in the expected sequence.

I would expect to see the test listed as following:
Testcase:0 [ xxxx ]
Testcase:1 [ xxxx ]
Testcase:2 [ xxxx ]
...
Testcase:10 [ xxxx ]
Testcase:11 [ xxxx ]

However, the Sorting is considering the figure after the "::" a string, and not an integer. Therefore "10" comes right after "1" instead of after "9". See attached picture.

![image](https://user-images.githubusercontent.com/23657567/36020430-ee32c054-0d82-11e8-84a4-798d1c5506fe.png)

**Comment by csoltenborn** [comment]
I fear that this is out of scope of GTA: First, we are reporting the tests to VS in the order as executed by the Google Test framework (in case this impacts display in the test window, which I doubt). Second, we only report a display name to VS (together with a unique name, the executable, the source file and line number, see [here](https://github.com/csoltenborn/GoogleTestAdapter/blob/9d85a77dac4471e919e29151234c74613ff92d8d/GoogleTestAdapter/TestAdapter/DataConversionExtensions.cs#L42)). The tests are then displayed by the VS test platform - we cannot influence how that is done.

You might however consider creating a feature request at the VS test platform's [repository](https://github.com/Microsoft/vstest) - for instance, it would probably suffice to apply some kind of natural sorting to the test cases (in contrast to "asciibetical" sorting).

Closing with *cantfix*...
