### ISSUE TITLE
gmock support

### ISSUE THREAD

**Issue by zahirtezcan** [csoltenborn/GoogleTestAdapter#198]
Do you plan to add support for google mocks? It's [main page](https://github.com/google/googlemock) suggests that it is absorbed into GoogleTest.

**Comment by csoltenborn** [comment]
What kind of support do you have in mind? After all, gmock is "only" an awesome mocking framework, and GTA is "only" an integration for gtest into VS. In other words: gmock does not have any influence on the actual test discovery and execution as far as I know. You can already use gmock with your gtest tests, and GTA will happily discover and execute those tests.

Having said that, I will (when time allows) provide some project and item templates for setting up gtest projects (#177), and they will in fact also come with support for gmock.

**Comment by zahirtezcan** [comment]
I was thinking about the templates and possible future version mismatch. Since, you are already planning to update templates with mock support, my concerns aren't an issue.
