### ISSUE TITLE
Support environment variables as placeholders

### ISSUE THREAD

**Issue by csoltenborn** [csoltenborn/GoogleTestAdapter#202]
In #201, the suggestion came up to support environment variables for the *Path Extension* option. This should also be supported for *Working Dir*, *Additional PDBs*, *Additional test execution params* and the setup/teardown batches.

**Comment by csoltenborn** [comment]
@dmcminn Would you mind to give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.3.1027/artifacts) a try?

**Comment by dmcminn** [comment]
Apologies for the delay in replying, it took a while to test.

I have defined an environment variable %GTA_TEST% as C:\Users\xxxx\Documents\dev\Test\GTA
In all these tests I set the options from the Tool/Options menu in VS and tested them. I then removed them from the global options and set them via a solution settings file and tested again.
The settings I used in both cases were just a simple single environment variable:

    Additional PDBs = %GTA_TEST%\Test.pdb

    <AdditionalTestExecutionParam>%GTA_TEST%</AdditionalTestExecutionParam>
    <BatchForTestSetup>%GTA_TEST%\setUp.bat</BatchForTestSetup>
    <BatchForTestTeardown>%GTA_TEST%\tearDown.bat</BatchForTestTeardown>
    <PathExtension>%WX30%\lib\vc140_dll</PathExtension>
    <WorkingDir>%GTA_TEST%</WorkingDir>


The results are:

PATH Extension accepts environment variables and can run my test executable with the external library DLLs in its own path.

Additional test execution params expands correctly when specified using environment variable.

Additional PDBs
I could not seem to set the Additional PDB path in the solution settings file, I could not find the node name to use. So I was only able to test it using the global options. When I type a path into the global options with an environment variable e.g. %GTA_TEST%\Test.pdb I get the following error:

    Invalid regular expression "%GTA_TEST%\Test.pdb", exception message: parsing "%GTA_TEST%\Test.pdb" - Unrecognized escape sequence \T.

but given the error message I suspect this has always been present. I can click on "OK" to the error dialog and the text stays in the option, but then I cannot click on "OK" to close the options dialog (I get the error dialog again). I have to put \\ in for the path separator. I understand why it happens using regular expressions to parse the additional PDBs but I did not see any documentation saying to beware of that.

Apart from that error dialog shown in the UI the Additional PDBs option loaded the PDB from the file correctly when specified using an environment variable.

The setup/teardown batch file locations always seem to be relative to the solution directory, so if I set those to %GTA_TEST%\setUp.bat and %GTA_TEST%\tearDown.bat then those batch files are not found as it is looking in a path such as C:\Users\xxxx\Documents\dev\solution\C:\Users\xxxx\Documents\dev\Test\GTA\setUp.bat

The Working Dir worked correctly when specified using an environment variable.

**Comment by csoltenborn** [comment]
Thanks for testing! I will have a look at it probably this evening...

**Comment by csoltenborn** [comment]
Thanks once more for testing so thoroughly! I have fixed the issues you found - if you want to give it another shot, please use [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.3.1035/artifacts). Note that I haven't touched anything despite the validation of correct *Additional PDBs* format and the setup/teardown batch file options being interpreted locally.

In fact, *Additional PDBs* had not yet been released - its first version indeed used regexes, and that validation hadn't been changed accidentally (and it that sense the problem had "always be present" ;-) ), and that's why it is not yet contained in the sample file on master branch. Here's a [link](https://github.com/csoltenborn/GoogleTestAdapter/blob/466cb8f27ff5dd44eb6010ffa44b22f1380a4713/GoogleTestAdapter/Resources/AllTestSettings.gta.runsettings) to the new version of that file.

**Comment by dmcminn** [comment]
Apologies for the delay in getting back to you. I've tested it again, both from the Tools\Options and the solution setting file, and all seems to be working as expected. Thank you for the explanation about Additional PDBs and the link to the new sample file.

**Comment by csoltenborn** [comment]
Great, and thanks once more for testing!
