### ISSUE TITLE
Error message from adapter when no C++ test's exists

### ISSUE THREAD

**Issue by OsirisTerje** [csoltenborn/GoogleTestAdapter#205]
I see the following error message for solution with no C++ tests:
![image](https://user-images.githubusercontent.com/203432/37704026-ed73699a-2cf7-11e8-8081-0c466f1160fd.png)
The message should not appear when there are no C++ tests.

**Comment by csoltenborn** [comment]
That's true - however, VS is responsible for invoking the adapter, and it's thus a bit surprising that this happens. You can enable debug mode to (hopefully) get more information on what's going on.

Despite that, you are not using GTA (hosted within this repository), but [TAfGT](https://github.com/Microsoft/TestAdapterForGoogleTest), the MS clone of GTA which is delivered through the VS installer. Please open an issue over there (and/or give GTA a try and re-open this issue if it also happens with GTA).

**Comment by OsirisTerje** [comment]
Thanks!  I'll raise the issue there.
