### ISSUE TITLE
discovery not detected for EXE with 'Debug' configuration

### ISSUE THREAD

**Issue by obi0ne** [csoltenborn/GoogleTestAdapter#208]
Hi,

Installed on my PC version 0.12.3 on VS2017 Enterprise v15.3.2,
and there seem to be issue with discovery of tests for EXE built under "debug" configuration.
If i build with "Release" configuration then all tests appear on "Test Explorer" with no problems.
However same test built with "Debug" configuration does not discover any test...

Attempt to place a xxxx.exe.is_google_test file with size 0bytes on target folder did not seem to solve it.

**Comment by obi0ne** [comment]
For some unexplained reason now it works, maybe PC restart solved the issue.

**Comment by csoltenborn** [comment]
Ok - thanks for letting me know!
