### ISSUE TITLE
No tests discovers with standalone vstest.console.exe

### ISSUE THREAD

**Issue by smadala** [csoltenborn/GoogleTestAdapter#218]
- Create Simple google test adapter test project.
- Run the tests with standalone vstest.console.exe which can be obtained from [Nuget.org](https://www.nuget.org/packages/Microsoft.TestPlatform/15.8.0-preview-20180605-02), Path to vstest.console.exe is `tools\net451\Common7\IDE\Extensions\TestPlatform`.

**Expected behavior**
- Test should get discovered and run.

**Actual behavior**
-  No test is available in `<path_to_assembly>`. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

**Root cause**
- Failed to load Microsoft.VisualStudio.TestWindow.Interfaces assembly(See stacktrace below).

```
TpTrace Warning: 0 : 31632, 3, 2018/06/11, 15:07:57.969, 5598455080321, testhost.exe, TestPluginDiscoverer: Failed to get types from assembly 'GoogleTestAdapter.TestAdapter, Version=0.12.3.994, Culture=neutral, PublicKeyToken=8d7bc984b03f1caf'.  Skipping test extension scan for this assembly.  Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginDiscoverer.cs:line 168
TpTrace Warning: 0 : 31632, 3, 2018/06/11, 15:07:57.969, 5598455082252, testhost.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginCache.cs:line 509
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(Object sender, Object eventArgs) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.PlatformAbstractions\net451\Runtime\PlatformAssemblyResolver.cs:line 74
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

**Proposed fix**
- Remove Microsoft.VisualStudio.TestWindow.Interfaces dependency for  GoogleTestAdapter.TestAdapter. Like [Chutzpah test adapter](https://www.nuget.org/packages/Chutzpah/) .
- `Microsoft.VisualStudio.TestWindow.Interfaces` contains API related to UI components(Test explorer). This assembly not ships with standalone vstest.console.exe.

**Additional data**
- [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform/15.8.0-preview-20180605-02) package used extensively in CI/CD pipeline(build agents without VS installed ) both internally and external to Microsoft.
- This issue blocking us to on board some of teams to CloudBuild(Microsoft internal distributed build system)

**Comment by csoltenborn** [comment]
Thanks for the great issue! I will have a look, but it will take some time, I fear...

**Comment by smadala** [comment]
@csoltenborn Thanks for acknowledging the issue. Can you share tentative timeline in your mind for fix?

**Comment by csoltenborn** [comment]
Sorry I don't have one right now... I will release 0.13.0 in the next, say, two weeks, so I think at least a couple of weeks.

Feel free to provide a pull request, though, if you want to speed up things ;-)

**Comment by smadala** [comment]
Couple of weeks sounds good. Thanks!

**Comment by csoltenborn** [comment]
I have removed the `TestWindow.Interfaces` dependency from the TestAdapter project - if you want, you can give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.0.1079/artifacts) a try to make sure that it indeed works for your use case.

I've seen that you are working on the VsTest project - any chance that you could have a look at #184 (any maybe also #217)?

**Comment by smadala** [comment]
@csoltenborn 
> I have removed the TestWindow.Interfaces dependency from the TestAdapter project - if you want, you can give this version a try to make sure that it indeed works for your use case.

Thank you so much for fixing it so fast. I will try it and let you know ASAP. 

> I've seen that you are working on the VsTest project - any chance that you could have a look at #184 (any maybe also #217)?

Thank you for noticing it. Sure, I will look into them and get back to you by end of week. 

I don't see any PR link to this issue.  Can you link the PR which fixed this issue? I would like to see the fix 😄 .

**Comment by csoltenborn** [comment]
Of course, here you are: it's PR #222. Do you want to do a formal GitHub code review?

Thanks for looking at the other issues - #184 in particular is very annoying to my users..

**Comment by smadala** [comment]
@csoltenborn I have tested. It works perfectly(Tested only on CLI). Make sure you have tested vsix(Test explorer) scenario.

> Of course, here you are: it's PR #222. Do you want to do a formal GitHub code review?

Just want to see how much big was the change(I was hesitated to create a PR 😄). It is always nice to have link issue in PR description, So that user can get to see the fix without going through all the PRs.

**Comment by csoltenborn** [comment]
Ok, thanks, and I will test ;-)
