### ISSUE TITLE
Accessing properties in custom property sheets for PATH extension

### ISSUE THREAD

**Issue by slnovak** [csoltenborn/GoogleTestAdapter#219]
Hello!

Thanks for maintaining this great project!

I'm using v12.3 (from the Release page on Github) for a project and am having difficulty getting the `PATH Extension` option to run correctly. I have a custom property sheet, generated by Conan, which contains a property `ConanBinaryDirectories` that contains a semi-colon-delimited list of directories that may contain .dll files that required to be loaded at runtime for the test executable to run correctly. This property sheet is added added to the "test" project that contains the tests I want to run. After setting the `PATH Extension` field in the options for GTA to `$(ConanBinaryDirectories)`, the "Run All" link fails due to `tests.exe` not being able to run. However, replacing `$(ConanBinaryDirectories)` with the raw/interpolated value from the propertysheet (i.e., the list of folders), the "Run All" link runs as expected.

Is it possible to update GTA's options dialog to allow properties specified from custom property sheets? Do you have any suggestions for a workaround if not?

Thanks!

**Comment by csoltenborn** [comment]
Thanks for the kudos :-)

Property sheets are not supported afaik (see #175 which I think is related). Possible workarounds:
* The upcoming release of GTA will support global environment variables (I do not believe that the property sheets' vars will be added to them, but you could at least give it a try - I do not have any experience with that)
* You could maybe make use of the `$(SolutionDir)` placeholder in case you can provide your binary directories in relation to that dir, or the `$(ExecutableDir)` placeholder to find them in relation to the test executable. Note that the the `$(SolutionDir)` placeholder is not yet provided at discovery time, but will be in the next version (which you can try [here](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.0.1073/artifacts))

Let me know whether this helps...

**Comment by slnovak** [comment]
Hi @csoltenborn,

That helps a lot! I reached out to one of the developers for Conan (conan-io/conan#3018) to express interest in having Conan export an environmental variable (via `setx.exe`) that will contain binary folder paths, which could be used at the system-level to extend `PATH` to include those directories.

In the short-term, I can manually hard-code my `PATH` to include those directories.

Thanks for the quick response and your contributions to improving the VS development environment! :beers:

**Comment by csoltenborn** [comment]
Sounds good - thanks for letting me know!
