### ISSUE TITLE
VS2013 Test Explorer shows incomplete results

### ISSUE THREAD

**Issue by kornman00** [csoltenborn/GoogleTestAdapter#22]
First of all, thanks for making GTA! And thanks in advance for improving it :o)

Now for the bugs:
1. When I run all, failed test cases don't properly appear (yet their space in the tree list seems to be consumed) while passed tests do. To be crystal clear, there's no 'Failed Tests' root node or children, as is the case with Passed Tests.
2. The formatting of instantiated test cases is cut off after the first forward slash in the test explorer tree list, but prints fine in the detail pane.

![image](https://cloud.githubusercontent.com/assets/1270047/12543319/f7d4d218-c2f3-11e5-8428-a7dd52e5911c.png)

The project I'm testing was the first thing I opened in VS after getting GTA. I immediately did "Run All Tests" and got output like the above. I then tried doing "Run Failed Tests" and still got the incomplete results (screenshot was from immediately after this action). VS Version/extension info follows:

Microsoft Visual Studio Premium 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Premium

Team Explorer for Visual Studio 2013   06191-004-0456033-02040
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06191-004-0456033-02040
Microsoft Visual Basic 2013

Visual C# 2013   06191-004-0456033-02040
Microsoft Visual C# 2013

Visual C++ 2013   06191-004-0456033-02040
Microsoft Visual C++ 2013

Visual F# 2013   06191-004-0456033-02040
Microsoft Visual F# 2013

CodeContractsHelper_Package   1.0
A package for the CodeContractsHelper extension.

Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GoogleTestExtensionOptionsPage Extension   1.0
GoogleTestExtensionOptionsPage Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2015.1.3   Build 102.0.20150724.141603
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

MicroProfiler   1.1.591.0
Realtime Instrumenting Profiler

Please, submit your questions, issues and suggestions to http://code.google.com/p/micro-profiler/issues/list
Copyright (c) 2011-2015 Artem Gevorkyan

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   2.8.60723.765
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

P4VS - Perforce Plugin for Visual Studio   2015.2.124.8831
P4VS is the Perforce integration for Microsoft Visual Studio. P4VS gives developers working in Visual Studio access to Perforce version control features.  P4VS gives you easy access to all of the Perforce version control tools and information you need to do your daily work. Check out, check in, see history, and more, directly from Visual Studio. P4VS is a fully compliant Visual Studio Integration Package, designed for full compatibility and ease of use. P4VS is built on P4API.NET, Perforce's fully supported API for the .NET environment. Perforce Software provides fast, robust version control to teams of all sizes working on any type of digital asset development.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

PVS-Studio   5.31.14891.5
PVS-Studio is a static code analyzer for C/C++ (Microsoft Visual Studio) with a simple licensing and pricing policies which is easy to install and use without a need to deploy complex maintenance environment.

Python Tools for Visual Studio   2.2.31124.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Profiling Support   2.2.31124.00
Profiling support for Python projects.

RegexTester   1.0
This is regular extension tester.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SyncfusionAssemblyReference   1.0
Information about my package

SyncfusionItemTemplates   1.0
Information about my package

Visual Assist   
For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2015 Whole Tomato Software, Inc.

Visual Studio Tools for Unity   2.1.0.0
Visual Studio Tools for Unity

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

**Comment by csoltenborn** [comment]
1. might be a duplicate of #15 (although the symptoms we've seen so far are a bit different) - can you please try to increase `WaitingPeriod` under `Options/Google Test Adapter/Advanced` or - even better - give the version a try which is linked at the very bottom of #15?
2. looks like a display problem of VS imho - we do not shorten testcase names at all. What happens if you increase the width of the test explorer such that the complete testcases' names fit into it? If this doesn't help, can you provide test code which results in the described behavior of the test explorer?

**Comment by kornman00** [comment]
Thanks!

1. Yeah, the VSIX in that link fixed the failed tests not showing up
2. So it seems that if VS can't fit the text after a "/" (that's then terminated by another "/" or the EOS) then it shortens everything after that "/" with "...". Pretty lame, but indeed a problem with VS itself, not GTA. Perhaps a replacement string could be provided in GTA's settings? Eg, instead of "/" a user could specify "->" or something else.

**Comment by csoltenborn** [comment]
Ok, thanks for trying! We will release that fixed version (which btw contains a workaround for an apparent bug of the VS test framework) in the next couple of days...

Shortening of test names: Hm, at least it's good to know that VS does this. We have full control over the names we are generating, but probably want to stuck with being consistent with the names Google Test itself uses. Still, a feature as you described could be a good idea... May I ask you to file an enhancement request (probably reusing the screenshot from this issue)?

And thanks for the feedback - glad I could help!
