### ISSUE TITLE
Output of a test unit is not printed in the "test" windows when debugging a test

### ISSUE THREAD

**Issue by aliha** [csoltenborn/GoogleTestAdapter#233]
If I run a test by right clicking on it then selecting "Debug Selected Tests" I don't see the test standard output in the output window under "Tests":
![image](https://user-images.githubusercontent.com/8523045/42458694-3a9c402c-8368-11e8-893c-6e839b3d1f2b.png)

Whereas running the same unit test, but by right clicking on it then selecting "Run Selected Tests" works fine:

![image](https://user-images.githubusercontent.com/8523045/42458708-45099262-8368-11e8-97c8-63f70dabed2a.png)

**Comment by csoltenborn** [comment]
This is due to the old execution framework (which I guess you have selected in options) - in debug mode an according warning is printed. Try the new execution framework...
