### ISSUE TITLE
Unable to list test cases : exit code 255 

### ISSUE THREAD

**Issue by williamchen1** [csoltenborn/GoogleTestAdapter#234]
Hello,

Until recently, I have been gratefully using all the features of Google Test Adapter.
However, when I add a new test case to an existing file, while being able to compile, GTA seems unable to list test cases as it returned a 255 exit code.

I also tried to run it through command line but, with the failed build, I am facing a segmentation fault.

Any lead on how to debug this is appreciated. Thanks in advance.
I updated VS recently, not sure if I should downgrade it.

**Comment by csoltenborn** [comment]
Trouble shooting section has a couple of hints on how to debug this. In particular, it sounds like your test executable has a problem - try to debug test discovery with `F5` as described there. If that doesn't help, let me know...

**Comment by williamchen1** [comment]
Thank you for your time.
I was dubious regarding some new definitions I added recently. 

The cause of the error was the use of extern objects whose definitions were to be found in the main.cpp which, I think, forced the main to be unwillingly part of the tests.

**Comment by csoltenborn** [comment]
Thanks for letting me know the cause!
