### ISSUE TITLE
UITests: try Azure

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#24]
There is an [Azure free trial](https://azure.microsoft.com/en-us/pricing/free-trial/) giving $200 credit for 1 month and the [Visual Studio Dev Essentials program](https://www.visualstudio.com/en-us/products/visual-studio-dev-essentials-vs.aspx) giving $25/month credits for 12 month.

$25 suffice for 166 hours of Basic A2 instance (2 cores, 3.5GB RAM, 60GB HDD) or 83 hours of Basic A3 instance (4 cores, 7GB RAM, 120GB HDD). See the [pricing calculator](https://azure.microsoft.com/en-us/pricing/calculator/).

**Comment by csoltenborn** [comment]
One obvious requirement is to test against all supported VS versions (see e.g. #42)...

**Comment by csoltenborn** [comment]
Closed since we neither have Azure resources nor the will to do any more UI testing :-)
