### ISSUE TITLE
Ability to use the working directory from the project file

### ISSUE THREAD

**Issue by EricLeeFriedman** [csoltenborn/GoogleTestAdapter#241]
GTA allows some macros such as $(SolutionDir), $(ExecutableDir), etc.... it would be nice if there was a $(ProjectWorkingDir) macro that would set the working directory of the test to that already set in the project file. This would come in handy especially when doing complicated project generation from a make file.

**Comment by csoltenborn** [comment]
Thanks for your feature request! #175 asks for the environment of the project settings, so I have tagged this `duplicate` (only) to collect "project setting requirements" under one issue...

**Comment by EricLeeFriedman** [comment]
Thank you!
