### ISSUE TITLE
Update SampleTests's gtest version to 1.8.1

### ISSUE THREAD

**Issue by Dark-Passenger** [csoltenborn/GoogleTestAdapter#248]
The google test nuget scripts don't include the gmock dlls in them, I agree while its a different project under google test it is officially one bundle and should be packaged as such in the adapter too.

Also the google test submodule is out of date and should now be targeting the newer 1.8.1 release 

as is visible here https://github.com/google/googletest/tree/release-1.8.1

also filed one for microsoft, I don't know which follows which 

#https://github.com/Microsoft/TestAdapterForGoogleTest/issues/137

**Comment by csoltenborn** [comment]
Thanks for your issue! However, the gest NuGet packages are maintained by MS (and are used e.g. by the project template they deliver with their flavor of the adapter, and which is not available for GTA).

Thus, I think that this is out of scope of GTA. I have therefore closed this issue - feel free to object...

**Comment by Dark-Passenger** [comment]
@csoltenborn Hi, okay well while I understand that it's something MS maintains as they package it the scripts are still a part of this repository that's why I filed it here, I don't know how it works (do they merge your repo into theirs or vice-versa or is it all independant development). Also the second issue of out of date gtest release ? is that also a part of nuget packaging ?

**Comment by csoltenborn** [comment]
We have set up our repositories such that they both contain the two adapters (there's a 'TestAdapterFlavor.props' file which configures the adapter to be built, see [build instructions](https://github.com/csoltenborn/GoogleTestAdapter/wiki/Development-Knowledge-Base#building-testing-debugging)). The idea was indeed to make merging between the two repositories as easy as possible.

The only way GTA uses the gtest code is as part of its SampleTests solution and automatic tests. That code will be updated to 1.8.1 at one point in time. You know what? Let's just use this issue to track that - I will rename the issue accordingly and re-open it.
