### ISSUE TITLE
New Version breaks on Visual Studio 2015/2017

### ISSUE THREAD

**Issue by CharonX2003** [csoltenborn/GoogleTestAdapter#250]
Visual Studio 2015, updated to Google Test Adapter 0.14.0.1212.

When opening a project Visual Studio opens the *"GoogleTestExtensionOptionsPage"-Paket was not loaded properly*.... popup.

**Comment by csoltenborn** [comment]
Apparently, VS 2017 has the same problem. I currently have no idea what's going on - might roll back this version in the next days if nothing helps. In the meantime, you can try to follow the "MEF cache corrupt" advise from the trouble shooting section (let me know if any of that helps).

If urgent, please install 0.13.4 manually and disable autimatic update.

**Comment by csoltenborn** [comment]
I have just released 0.14.1 which should fix this issue...
