### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by csoltenborn** [csoltenborn/GoogleTestAdapter#251]

**Comment by tapika** [comment]
Should this one be working with latest Visual studio 2019 release ?

I have checked that .net version is at least 4.7.2, GTA is currently compiled for .net 4.6 - wondering if VS still can use older version of .NET framework ?

**Comment by csoltenborn** [comment]
GTA supports VS >= VS2013 (TAfGT: >= VS2017). So far I haven't heard anything (and have used and tested GTA with VS2019), so I guess it should be fine...

**Comment by tapika** [comment]
Tested bit more. 
So Microsoft port / TAfGT seems to work with vs2019.
GTA does not work with vs2019, and .vsix does not even sees vs2019 being present (used .vsix from Market web page, cannot be downloaded online) - .vsix tries to install only under vs2017.

Microsoft port / TAfGT - however - what I have tried to pick TAfGT from https://github.com/Microsoft/TestAdapterForGoogleTest - that cannot be built by default.

I have checked also how GTA handles dependent assemblies, you seems to download them via nuget packages, 

https://github.com/csoltenborn/GoogleTestAdapter/blob/master/GoogleTestAdapter/VsPackage.GTA/packages.config#L18

how TAfGT is compiled still bit mystery for me.

Here is configured used .net framework:
https://github.com/Microsoft/TestAdapterForGoogleTest/blob/dev15/Common.props#L21

But currently it's 4.6 - but what I have tried out with currently officially released version of vs2019 - it should be .net 4.7.2.

Suspect either github build is not valid/ outdated, or I'm looking on wrong branch / fork.

Can we reopen vs2019 support again for GTA ?

**Comment by csoltenborn** [comment]
I cannot reproduce this - using VS2019, I have just now
* installed GTA via *Extensions > Manage extensions > Online*
* downloaded the GTA 0.15.0 VSIX and installed it.

Both installation did not have any problems, and I ended up with a working version of GTA in both cases.

Additionally, [this article](https://msdn.microsoft.com/en-us/magazine/mt493251.aspx) seems to imply that a VS extension indeed does have to be built against the framework version supported by the oldest VS version to be supported by that extension. Thus, I think referring to .NET 4.6 is indeed just fine...

Since I and many of my users do not appear to have issues running GTA against VS 2019, I don't want to reopen this issue - please feel free to open a new issue to deal with your particular problems if they continue to exist...

**Comment by tapika** [comment]
Hmm...  You're right. I had vs2019 installed on two machines, and on one of them VS Market did not work for some reason, suspect because it was vs2019 preview. I have now uninstalled and installed just released vs2019, and can confirm that GTA is working correctly there. But syncProj does not work out of box - same problems as specified in here: https://github.com/Microsoft/TestAdapterForGoogleTest/issues/159#issuecomment-483845312 

appears. Suspect it's not GTA nor TAfGT issue, but VS Test platform issue, will try to raise issue there somewhere...
