### ISSUE TITLE
Starting from 0.14.0 text lines are printed twice in the VS output window

### ISSUE THREAD

**Issue by aey76** [csoltenborn/GoogleTestAdapter#252]
Using VS2017 Pro version 15.7.6

**Comment by csoltenborn** [comment]
Thanks for your bug report! Can you please attach the output of a test run (preferrably as a file) with the debug option enabled? Thanks...

**Comment by csoltenborn** [comment]
Closed due to inactivity - feel free to reopen if problem remains.
