### ISSUE TITLE
Could not discover test cases

### ISSUE THREAD

**Issue by liixixi** [csoltenborn/GoogleTestAdapter#253]
Hi,
I have read the troubleshooting part, but I still could not get my test cases discovered.
The environment are VS2017, 15.8, GTA 0.14.2.
I have a Win32 dll project builtin google test/google mock framework, export a RunTest(argc, argv) function (with RUN_ALL_TESTS inside), then a normal Win32 console program to call the export function to run the google test.
MyRunner.exe --gtest_list_tests output: 
test_case_name.
  test_name
  test_name1

I have MyRunner.exe.is_google_test file at the same folder (output folder), and the dll has copied to the same folder.

Would someone help me how to troubleshot this problem next?

thanks
Simon

**Comment by csoltenborn** [comment]
Hi Simon, at least I will try ;-) Can you please enable debugging at GTA's settings and then upload the resulting output (preferrably as a file)?

**Comment by csoltenborn** [comment]
Closed due to inactivity - feel free to reopen of problem remains... And please share your solution if you solved the problem yourself.
