### ISSUE TITLE
Add support for GTEST_SKIP

### ISSUE THREAD

**Issue by sixten-hilborn** [csoltenborn/GoogleTestAdapter#260]
Hi,

gtest has a new feature `GTEST_SKIP` to dynamically skip tests (it's in master but no official release yet): https://github.com/google/googletest/pull/1544
However GTA doesn't recognize this and will report such tests as crashed. Sample test:

    TEST(Test, MyTest)
    {
        GTEST_SKIP();
    }

Gives this output:

    Message: 
    !! This test has probably CRASHED !!
    Test output:

    [  SKIPPED ] Test.MyTest (1 ms)

**Comment by csoltenborn** [comment]
Thanks for the report - should be relatively easy to support...

However, I do not have time at the moment to play around with different gtest versions - would you mind to attach the output of a test executable (i.e., if you run that executable on the command line) containing skipped tests to this issue?

**Comment by sixten-hilborn** [comment]
That would be great!
Here's a small sample and its output attached:
[test.cpp.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2821330/test.cpp.txt)
[output.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2821329/output.txt)
