### ISSUE TITLE
Add support for being able to debug test code launched via death test defines (EXPECT_EXIT, ...)

### ISSUE THREAD

**Issue by tapika** [csoltenborn/GoogleTestAdapter#277]
If you write function like this:

     void funcExit()
     {
         _exit(1);
     }

     TEST(TestCaseName, TestName1)
     {
         EXPECT_EXIT(funcExit(), testing::ExitedWithCode(1), "");

and set breakpoint in funcExit - that breakpoint is never reachable, as functionality is launched in child process.

Brief analysis shows that in windows there comes CreateProcess function call with same command parameters and main test 
application, with additional command line parameter:

    "--gtest_internal_run_death_test=...\googletest-release-1.8.0\googletest\src\gtest_main.cpp|35|1|22300|1012|1016"

where parameter arguments seems to be 

    <file>|<line>|<test index>|<process id>|<write handle>|<event handle>

Somewhere in:
ConsoleApplication3.exe!testing::internal::WindowsDeathTest::AssumeRole() Line 766
	at googletest-release-1.8.0\googletest\src\gtest-death-test.cc(766)

Theoretically attach to process could be handled by monitoring what application prints, parsing it out, and attaching to correspondent process

https://github.com/tapika/TestAdapterForGoogleTest/blob/master/GoogleTestAdapter/TestAdapterStarter/Program.cs#L69
https://github.com/tapika/TestAdapterForGoogleTest/blob/master/GoogleTestAdapter/TestAdapterStarter/Program.cs#L204
https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md

But this might require for child process to wait debugger attachment as well:

https://github.com/Microsoft/vstest/blob/06101ef5feb95048cbe850472ed49604863d54ff/src/testhost.x86/Program.cs#L85

In VS Test environment implementation is not so good, as you get halted in testhost.exe by Debugger.Break();

In Google test adapter we don't necessarily need any debug break.

Theoretically this system can spawn multiple child processes, but google unit test will not work correctly when you place EXPECT_EXIT in funcExit() - it can spawn only one level of child processes.

Brief analysis of google unit test starter uses write handle coming from creation of anonymous pipe:

https://github.com/google/googletest/blob/master/googletest/src/gtest-death-test.cc#L742

This approach is acceptable if application is started and terminated all the time, but eventually I would like to keep application alive despite of it being under test or just active and used by end-user - this places a requirement that pipes should not be anonymous anymore - I by myself have used pipes names, which are naming according to process id, which owns given pipe.

master process:
https://github.com/tapika/CsScriptHotReload/blob/master/scriptStarter/ScriptHost.cs#L189
child process:
https://github.com/tapika/CsScriptHotReload/blob/master/scriptStarter/ScriptHost.cs#L279
implementation:
https://github.com/tapika/CsScriptHotReload/blob/master/scriptStarter/IpcChannel.cs#L15

Debug attach process at the moment with my own prototype (CsScriptHotReload) is limited to Visual Studio and might be also Visual Studio version itself. Best way that GTA would perform debug attach, so google starter code would not need to do that one.

But to be able to keep application alive, we can either use Native debugging type or Managed debugging type, as Native+Managed (=mixed) debug type 
will by design terminate application after debug session.

https://github.com/tapika/CsScriptHotReload/blob/master/scriptStarter/ScriptHost.cs#L19
https://github.com/tapika/CsScriptHotReload/blob/master/scriptStarter/ScriptHost.cs#L42

https://github.com/tapika/TestAdapterForGoogleTest/blob/master/GoogleTestAdapter/VsPackage.Shared/Debugging/VsDebuggerAttacher.cs#L35

Need to analyze in depth if current debugger mode can be queried from some existing VS API's and just can be reused for all forthcoming debug attach function calls.

I will start analyze in depth how this can be implemented, but my focus will remain in C++ scripting functionality (launch devenv.exe as child process for C++ project building), and it's possible that I'll adjust also google unit starter and GTA as required.

Adding this as it's own issue, just to be able to discuss this subject bit deeper.

**Comment by csoltenborn** [comment]
I'm closing this for now - see #274...
