### ISSUE TITLE
Package GoogleTestExtensionOptionsPage wasn't correct downloaded.

### ISSUE THREAD

**Issue by jul-star** [csoltenborn/GoogleTestAdapter#281]
![image](https://user-images.githubusercontent.com/11502265/56643718-d3667680-6682-11e9-9154-f0e0bf7f3672.png)

ActivityLog.xml:
<description>Unexpected system error mode before loading package [GoogleTestExtensionOptionsPage]</description>
<description>SetSite failed for package [GoogleTestExtensionOptionsPage]Source: &apos;Microsoft.VisualStudio.Composition&apos; Description: &#x041E;&#x0436;&#x0438;&#x0434;&#x0430;&#x044E;&#x0442;&#x0441;&#x044F; &#x043E;&#x043F;&#x0435;&#x0440;&#x0430;&#x0446;&#x0438;&#x0438; &#x044D;&#x043A;&#x0441;&#x043F;&#x043E;&#x0440;&#x0442;&#x0430; (1) &#x0441; &#x043D;&#x0430;&#x0437;&#x0432;&#x0430;&#x043D;&#x0438;&#x0435;&#x043C; &#x043A;&#x043E;&#x043D;&#x0442;&#x0440;&#x0430;&#x043A;&#x0442;&#x0430; &quot;GoogleTestAdapter.TestAdapter.Settings.IGlobalRunSettingsInternal&quot;, &#x043D;&#x043E; &#x043F;&#x043E;&#x0441;&#x043B;&#x0435; &#x043F;&#x0440;&#x0438;&#x043C;&#x0435;&#x043D;&#x0435;&#x043D;&#x0438;&#x044F; &#x0441;&#x043E;&#x043E;&#x0442;&#x0432;&#x0435;&#x0442;&#x0441;&#x0442;&#x0432;&#x0443;&#x044E;&#x0449;&#x0438;&#x0445; &#x043E;&#x0433;&#x0440;&#x0430;&#x043D;&#x0438;&#x0447;&#x0435;&#x043D;&#x0438;&#x0439; &#x043D;&#x0430;&#x0439;&#x0434;&#x0435;&#x043D;&#x043E; 2.&#x000D;&#x000A;Microsoft.VisualStudio.Composition.CompositionFailedException: &#x041E;&#x0436;&#x0438;&#x0434;&#x0430;&#x044E;&#x0442;&#x0441;&#x044F; &#x043E;&#x043F;&#x0435;&#x0440;&#x0430;&#x0446;&#x0438;&#x0438; &#x044D;&#x043A;&#x0441;&#x043F;&#x043E;&#x0440;&#x0442;&#x0430; (1) &#x0441; &#x043D;&#x0430;&#x0437;&#x0432;&#x0430;&#x043D;&#x0438;&#x0435;&#x043C; &#x043A;&#x043E;&#x043D;&#x0442;&#x0440;&#x0430;&#x043A;&#x0442;&#x0430; &quot;GoogleTestAdapter.TestAdapter.Settings.IGlobalRunSettingsInternal&quot;, &#x043D;&#x043E; &#x043F;&#x043E;&#x0441;&#x043B;&#x0435; &#x043F;&#x0440;&#x0438;&#x043C;&#x0435;&#x043D;&#x0435;&#x043D;&#x0438;&#x044F; &#x0441;&#x043E;&#x043E;&#x0442;&#x0432;&#x0435;&#x0442;&#x0441;&#x0442;&#x0432;&#x0443;&#x044E;&#x0449;&#x0438;&#x0445; &#x043E;&#x0433;&#x0440;&#x0430;&#x043D;&#x0438;&#x0447;&#x0435;&#x043D;&#x0438;&#x0439; &#x043D;&#x0430;&#x0439;&#x0434;&#x0435;&#x043D;&#x043E; 2.&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()&#x000D;&#x000A;   &#x0432; GoogleTestAdapter.VsPackage.GoogleTestExtensionOptionsPage.&lt;&gt;c__DisplayClass14_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- &#x041A;&#x043E;&#x043D;&#x0435;&#x0446; &#x0442;&#x0440;&#x0430;&#x0441;&#x0441;&#x0438;&#x0440;&#x043E;&#x0432;&#x043A;&#x0430; &#x0441;&#x0442;&#x0435;&#x043A;&#x0430; &#x0438;&#x0437; &#x043F;&#x0440;&#x0435;&#x0434;&#x044B;&#x0434;&#x0443;&#x0449;&#x0435;&#x0433;&#x043E; &#x0440;&#x0430;&#x0441;&#x043F;&#x043E;&#x043B;&#x043E;&#x0436;&#x0435;&#x043D;&#x0438;&#x044F;, &#x0433;&#x0434;&#x0435; &#x0432;&#x043E;&#x0437;&#x043D;&#x0438;&#x043A;&#x043B;&#x043E; &#x0438;&#x0441;&#x043A;&#x043B;&#x044E;&#x0447;&#x0435;&#x043D;&#x0438;&#x0435; ---&#x000D;&#x000A;   &#x0432; System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   &#x0432; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()&#x000D;&#x000A;--- &#x041A;&#x043E;&#x043D;&#x0435;&#x0446; &#x0442;&#x0440;&#x0430;&#x0441;&#x0441;&#x0438;&#x0440;&#x043E;&#x0432;&#x043A;&#x0430; &#x0441;&#x0442;&#x0435;&#x043A;&#x0430; &#x0438;&#x0437; &#x043F;&#x0440;&#x0435;&#x0434;&#x044B;&#x0434;&#x0443;&#x0449;&#x0435;&#x0433;&#x043E; &#x0440;&#x0430;&#x0441;&#x043F;&#x043E;&#x043B;&#x043E;&#x0436;&#x0435;&#x043D;&#x0438;&#x044F;, &#x0433;&#x0434;&#x0435; &#x0432;&#x043E;&#x0437;&#x043D;&#x0438;&#x043A;&#x043B;&#x043E; &#x0438;&#x0441;&#x043A;&#x043B;&#x044E;&#x0447;&#x0435;&#x043D;&#x0438;&#x0435; ---&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   &#x0432; Microsoft.VisualStudio.Services.VsTask.GetResult()</description>

Clearing the cache with Clear MEF Component Cache by Mads Kristensen Does NOT Help.

**Comment by csoltenborn** [comment]
My assumption is that you have installed GTA and TAfGT in parallel. The latter is MS' clone of GTA, and MS has unfortunately forgotten to change the GUID of their adapter's options package, which might lead to such problems if I remember correctly. Please let me know whether this fixes the issue...

**Comment by jul-star** [comment]
No it is not. See the print screen: 
![image](https://user-images.githubusercontent.com/11502265/56722624-28bc8980-6750-11e9-8970-3828c622c25e.png)
Thanks for a hint. (I didn't know it's a clone of your plugin)

**Comment by jul-star** [comment]
How about those two:
![image](https://user-images.githubusercontent.com/11502265/56723186-273f9100-6751-11e9-9953-2d8b0d61260b.png)
Could they interfere with each other?

**Comment by csoltenborn** [comment]
To be honest, I don't know tto much abou the TAfGT adapter, but yes, I guess that's the problem. Uninstall one of products, and the other will be fine. GTA is more advanced and has (much) better support, TAfGT comes with Visual Studio (so no need to manually install GTA). You decide...

**Comment by jul-star** [comment]
Thanks a lot. Deleting 0.10.1.7 make GTA works.

**Comment by csoltenborn** [comment]
Sweet, thanks for letting me know...
