### ISSUE TITLE
No logging output using spdlog

### ISSUE THREAD

**Issue by watho** [csoltenborn/GoogleTestAdapter#289]
Hi,

i am using the logging framework [spdlog](https://github.com/gabime/spdlog) and can't find a way to display the logging output.

Using the provided stdout and stderr logger i can see the output when running the tests without GoogleTestAdapter e.g. when running the compiled exe-file. With GTA they are not shown neither in the testexplorer window nor in the test output. Normal std::cout and std::cerr output is visible. Is there perhaps any setting that i am missing?

**Comment by csoltenborn** [comment]
GTA parses the output produced by the test executable. Output generated by a particular test case should end up in that test case's output in the test explorer. See sample test suite for examples of such tests.

Do you see your output in the test output window when enabling option *Print test output*?

**Comment by watho** [comment]
Thank you for the answer. No, the output is not visible in the test output window.

**Comment by watho** [comment]
I have a working solution now using the uncoloured stdout logger. spdlog is using a coloured output per default.

I have some styling issues and the coloured output would be nice to have, but that's more a feature request than a bug for which i might open a separate ticket. So i am closing this ticket.

**Comment by csoltenborn** [comment]
Ok, thanks for letting me know!
