### ISSUE TITLE
[QUESTION] How can I install the extension without Visual Studio?

### ISSUE THREAD

**Issue by tithefug** [csoltenborn/GoogleTestAdapter#290]
Hello,

   We are using the Google Test Adapter for our testing suite in our application.  This works great on all development machines that have Visual Studio installed.  I was wondering how we can execute these tests on a QA machine where Visual Studio is not installed.  VSTest.Console is available as a standalone package, but I can't figure out how to install VS Extensions without having VS installed.

Any help would be greatly appreciated.

Thanks,

Cappy

**Comment by csoltenborn** [comment]
Make use of the NuGet version of this extension:
* Add an entry such as the following to your test projects' `packages.config` files:
`<package id="GoogleTestAdapter" version="0.16.1" targetFramework="native" developmentDependency="true" />`
* Use *Visual Studio Test* tasks within your Azure DevOps builds as appropriate

This should do the trick... Let me know what your results are.

**Comment by csoltenborn** [comment]
Closed due to inactivity.
