### ISSUE TITLE
Possibility to install/use without admin privileges

### ISSUE THREAD

**Issue by FlorianWolters** [csoltenborn/GoogleTestAdapter#291]
Is it possible to install and use Google Test Adapter without administrative privileges?

Trying to execute `GoogleTestAdapter-0.16.1.vsix` using a Microsoft Visual Studio 2017 15.5.4 installation opens a UAC prompt. After authentification with the local non-admin user a dialog containing the following is displayed:

   Supplying the /installas command line parameter requires that vsixinstaller is run as admin.

Is any workaround available or is usage impossible without admin installation?

**Comment by csoltenborn** [comment]
I'm not aware of anything special about the GTA installation (compared to other extensions), and I cannot reproduce this with my local VS2019 installation (my user is admin, but the .vsix file should not be run as admin by default, I believe). 

Do you have the same problem with every extension (in particular with test adapters)? My guess would be that during installation, some folders need to be accessed which require admin rights on your machine...

**Comment by FlorianWolters** [comment]
I've check with `TestAdapterForGoogleTestv0.10.1.0.vsix`. Same problem. I do not have that problem with non test adapter VSIX files. Shouldn't it be generally possible to install the extension to `%LOCALAPPDATA\Microsoft\VisualStudio\15.0_c5c2c691\Extensions` wihtout admin rights? Or is there anything special for test adapters that requires write access to `%PROGRAMFILES(X86)%\Microsoft Visual Studio 12.0\Common7\IDE\Extensions`? The possibility to use it without admin rights would be a huge plus point. Otherwise the central IT department is required in organizations to install the VSIX.

**Comment by csoltenborn** [comment]
To be honest, I have no idea. However, since `TestadapterForGoogleTest` is provided by MS, we can safely assume that the behavior is as expected. I guess that you will have to live with that restriction...

However, one alternative could be to include GTA as a NuGet dependecy into your solution. However, this has some srious restrictions (see docs) and thus probably isn't the way to go.
