### ISSUE TITLE
[QUESTION] Can <AdditionalTestExecutionParam> in RunSettings be used to pass command line arguments to the Google Test EXE?

### ISSUE THREAD

**Issue by tithefug** [csoltenborn/GoogleTestAdapter#292]
I'm looking for a way to pass arguments to my executable via the RunSettings file.  Is this possible using \<AdditionalTestExecutionParam\>, or by some other means?

Thanks,

Cappy

**Comment by csoltenborn** [comment]
Yes, it is.  For a demonstration, have a look at the SampleTests solution, in particular the [settings file](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/SampleTests/SampleTests.gta.runsettings) and [this file](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/SampleTests/Tests/Main.cpp).

**Comment by tithefug** [comment]
Great!  Thanks!  I'll play around with it.
