### ISSUE TITLE
[QUESTION] How to implement Traits?

### ISSUE THREAD

**Issue by tithefug** [csoltenborn/GoogleTestAdapter#293]
I was wondering if you could help me with Traits.

Are they returned when listing tests, or only after execution?

Can you provide an example implementation?  The link in the ReadMe [1] is no longer valid.

Thanks,

Cappy

[1] - https://github.com/csoltenborn/GoogleTestAdapter/blob/master/GoogleTestAdapter/Core.Tests/AbstractGoogleTestDiscovererTraitTests.cs

**Comment by csoltenborn** [comment]
Once more, have a look at the SampleTests solution. Traits are used at a couple of places, e.g. [here](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/SampleTests/Tests/BasicTests.cpp) or [here](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/SampleTests/Tests/FixtureTests.cpp).

**Comment by tithefug** [comment]
Thanks!
