### ISSUE TITLE
Debugging a test from Test Explorer does not work anymore in visual studio 2015

### ISSUE THREAD

**Issue by bjberendsen** [csoltenborn/GoogleTestAdapter#298]
Debugging a test from Test Explorer does not work anymore in visual studio 2015 after the latest update (0.17.0.1387) of the GoogleTestAdapter. Running tests from the Test Explorer goes fine however debugging a test gives an error in the test output. After uninstalling GoogleTestAdapter and installing the previous version 0.15.0.1305 manually using the vsix it worked again. I have encountered the problem at two different pc's with visual studio 2015. See test output:
```
------ Run test started ------
[12:53:33.520] Google Test Adapter: Test execution starting...
[12:53:33.589 ERROR] Debugging is only possible if GoogleTestAdapter has been installed into Visual Studio - NuGet installation does not support this (and other features such as Visual Studio Options, toolbar, and solution settings).
[12:53:33.597 ERROR] 
================
The following warnings and errors occured during test execution (enable debug mode for more information):
[12:53:33.589 ERROR] Debugging is only possible if GoogleTestAdapter has been installed into Visual Studio - NuGet installation does not support this (and other features such as Visual Studio Options, toolbar, and solution settings).
========== Run test finished: 0 run (0:00:42,3886996) ==========
```

**Comment by csoltenborn** [comment]
I am not aware of any changes with respect to that behavior in 0.17.0. I just quickly checked the [PR](https://github.com/csoltenborn/GoogleTestAdapter/pull/297/files) again, and am pretty confident about that (most changes are about the tests of GTA, and the only behavioral change is in `TestResultCollector.cs`).

 Can you please try with version 0.16.1 (which is the actual previous version, 0.15.0 is older)?

**Comment by bjberendsen** [comment]
With version 0.16.1.1369 it also works fine.

**Comment by psxlover** [comment]
I also run into this. After restarting VS and getting the update I'm getting that error if I try to right click a test and use "Debug Selected Tests".

**Comment by csoltenborn** [comment]
Oh boy - I think I've discovered the issue. Stupid me...

Please use 0.16.1 for now - fixed version will follow at the weekend.
