### ISSUE TITLE
Allow using command line arguments from project debugging settings for test execution

### ISSUE THREAD

**Issue by Knitschi** [csoltenborn/GoogleTestAdapter#299]
I would like to have an option in the GTA that allows using the same command line parameters that are defined in the projects debugging settings.

This would remove the need to duplicate the arguments between the two settings and also work well together with CMake which allows to set this project property via the [`VS_DEBUGGER_COMMAND_ARGUMENTS`](https://cmake.org/cmake/help/latest/prop_tgt/VS_DEBUGGER_COMMAND_ARGUMENTS.html) property.

I know that this feature is also mentioned in #175 but I thought it would be better to have a separate ticket for it.

**Comment by csoltenborn** [comment]
Assuming that your particular setting is available as a VS macro (which I believe it is), this is in fact already possible: [docs](https://github.com/csoltenborn/GoogleTestAdapter#settings-helper-files), [sample code](https://github.com/csoltenborn/GoogleTestAdapter/tree/master/SampleTests/HelperFileTests).

**Comment by Knitschi** [comment]
Ok the macro is `$(LocalDebuggerCommandArguments)`. I will still have to generate the settings files then I guess and use the macro in there.

**Comment by csoltenborn** [comment]
Exactly! Add an expression such as

`echo DebuggerArgs=$(LocalDebuggerCommandArguments) > $(TargetPath).gta_settings_helper`

to your project's post-build event, then use placeholder `$(DebuggerArgs)` within option *AdditionalTestExecutionParam* of your GTA settings file. Let me know if it works as desired - I might add this as an example to the docs.
