### ISSUE TITLE
Test output is not printed in the "test" window

### ISSUE THREAD

**Issue by aliha** [csoltenborn/GoogleTestAdapter#300]
I have set `Print test output` to `True` but I still do not get any output in my test output window.
If a test fails/crashes I see the output in "Test Detail Summary window" as part of "Test Explorer".

It used to work fine. I did not change any settings but recently I updated Visual Studio 2019 from 16.3.2 to 16.3.4 and also GoogleTestAdapter has been updated to 0.17.0.1387.

Update: I reverted GoogleTestAdapter to 0.16.1 and everything works fine.

![image](https://user-images.githubusercontent.com/8523045/66674097-21bb0200-ec30-11e9-9be7-298a9b305d4e.png)

**Comment by csoltenborn** [comment]
This has the same cause as #298 (broken options and debugging). Fix will be released today. Sorry for the inconvenience...
