### ISSUE TITLE
The 'GoogleTestExtensionOptionsPage' package did not load correctly.

### ISSUE THREAD

**Issue by OfekShilon** [csoltenborn/GoogleTestAdapter#301]
In VS2019 i consistently get this message.
The solution [posted here](https://github.com/csoltenborn/GoogleTestAdapter/issues/172) doesn't help. The MEF error log shows:

----- CompositionError level 1 ------
Microsoft.CodeAnalysis.ExternalAccess.FSharp.Internal.Editor.FSharpSynchronousIndentationService.ctor(service): expected exactly 1 export matching constraints:
    Contract name: Microsoft.CodeAnalysis.ExternalAccess.FSharp.Editor.IFSharpSynchronousIndentationService
    TypeIdentityName: Microsoft.CodeAnalysis.ExternalAccess.FSharp.Editor.IFSharpSynchronousIndentationService
but found 0.
   part definition Microsoft.CodeAnalysis.ExternalAccess.FSharp.Internal.Editor.FSharpSynchronousIndentationService

GoogleTestAdapter.TestAdapter.Settings.RunSettingsService.ctor(globalRunSettings): expected exactly 1 export matching constraints:
    Contract name: GoogleTestAdapter.TestAdapter.Settings.IGlobalRunSettings
    TypeIdentityName: GoogleTestAdapter.TestAdapter.Settings.IGlobalRunSettings
but found 2.
    GoogleTestAdapter.TestAdapter.Settings.GlobalRunSettingsProvider
    GoogleTestAdapter.TestAdapter.Settings.GlobalRunSettingsProvider
   part definition GoogleTestAdapter.TestAdapter.Settings.RunSettingsService

GoogleTestAdapter.TestAdapter.Settings.RunSettingsService.ctor(globalRunSettings): is not assignable from exported MEF value GoogleTestAdapter.TestAdapter.Settings.GlobalRunSettingsProvider.
   part definition GoogleTestAdapter.TestAdapter.Settings.RunSettingsService

GoogleTestAdapter.TestAdapter.Settings.RunSettingsService.ctor(globalRunSettings): expected exactly 1 export matching constraints:
    Contract name: GoogleTestAdapter.TestAdapter.Settings.IGlobalRunSettings
    TypeIdentityName: GoogleTestAdapter.TestAdapter.Settings.IGlobalRunSettings
but found 2.
    GoogleTestAdapter.TestAdapter.Settings.GlobalRunSettingsProvider
    GoogleTestAdapter.TestAdapter.Settings.GlobalRunSettingsProvider
   part definition GoogleTestAdapter.TestAdapter.Settings.RunSettingsService

GoogleTestAdapter.TestAdapter.Settings.RunSettingsService.ctor(globalRunSettings): is not assignable from exported MEF value GoogleTestAdapter.TestAdapter.Settings.GlobalRunSettingsProvider.
   part definition GoogleTestAdapter.TestAdapter.Settings.RunSettingsService

**Comment by csoltenborn** [comment]
Do you have *Test Adapter for Google Test* installed by any chance? It's the MS clone of this test adapter which comes with VS, and MS has forgotten to change the adapter's option's GUID, so they can't be installed in parallel.

**Comment by OfekShilon** [comment]
That is indeed the case.. Thanks a lot for the prompt reply!

**Comment by csoltenborn** [comment]
Well, that's one advantage of using GTA in contrast to using TAfGT ;-)
