### ISSUE TITLE
Test duration isn't set when running gtest with GTA using Visual Studio Tests task

### ISSUE THREAD

**Issue by Orkanr** [csoltenborn/GoogleTestAdapter#304]
Hello!
We use Google Test Adapter to run our gtest C++ tests in Azure DevOps using task Visual Studio Tests. 
And currently found issue with duration time of these tests: always equals to 0.
Runsettings file:
```xml
<RunSettings>
  <RunConfiguration>
    <TestAdaptersPaths>.\GoogleTestAdapter</TestAdaptersPaths>
  </RunConfiguration>
  <GoogleTestAdapterSettings>
    <SolutionSettings>
      <Settings>
        <OutputMode>Verbose</OutputMode>
      </Settings>
    </SolutionSettings>
    <ProjectSettings>
      <Settings ProjectRegex=".*ProjectTestsName.exe">
        <WorkingDir>C:\Program Files\ProductName</WorkingDir>
      </Settings>
    </ProjectSettings>
  </GoogleTestAdapterSettings>
</RunSettings>
```
GoogleTestAdapter folder contains the last GTA build version 0.17.1.1389.

ProjectName.exe.gta.testdurations is properly created: 
```xml
<GtaTestDurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Executable>C:\Autotests\TestBinaries\ProjectTestsName.exe</Executable>
  <TestDurations>
    <TestDuration Test="Operation/TestCase/0" Duration="2487" />
    <TestDuration Test="Operation/TestCase/1" Duration="5783" />
    <TestDuration Test="Operation/TestCase/2" Duration="6537" />
    <TestDuration Test="Operation/TestCase/3" Duration="1826" />
    <TestDuration Test="Operation/TestCase/4" Duration="23101" />
  </TestDurations>
</GtaTestDurations>
```
But the final .trx file of these test run contains some strange info, something like this (this behavior occured for all tests): 

duration="00:00:01.9290000" 
startTime="2019-11-07T08:23:02.3521789+01:00" 
endTime ="2019-11-07T08:23:02.3521789+01:00"

startTime and endTime are same.

And in CI duration time is set to zero, because according to the description of task 'Publish Test Results', "Duration is used only when Date started and Date completed are not available". And it seems, this logic also used inside 'Run Functional Tests' task

Also, we have MS tests with following runsettings file:
```xml
<RunSettings>
  <MSTest>
    <AssemblyResolution>
      <Directory path="C:\Program Files\ProductName"/>
    </AssemblyResolution>
  </MSTest>
</RunSettings>
```
And final .trx file has correct values something like this:
duration="00:01:04.7560151" 
startTime="2019-11-04T10:41:14.9490983+01:00" 
endTime ="2019-11-04T10:42:20.9794123+01:00"

Do you know what is it and how to fix it?
Thanks.

P.S. It's a general partial report view of our tests:
![image](https://user-images.githubusercontent.com/57482578/68386503-d62f4180-0164-11ea-90d1-abdc2ae3f06c.png)

**Comment by csoltenborn** [comment]
The `ProjectName.exe.gta.testdurations` file is only used internally by GTA for distributing the tests accross different threads in case of parallel execution (the assumption being that each individual test will take about the same time per test run).

Despite that, all GTA does is reporting the test results to Visual Studio - displaying them in Test Explorer as well as serializing them as a `.trx` file is up to Visual Studio.

Thus, my question is:  Are the test durations displayed correctly in the test explorer when your tests are run within Visual Studio?

Note that we are also using GTA to run gtest tests within Azure Devops builds, and the durations appear to be displayed just fine. If the durations are correct within VS, then we might want to check out your build configuration...

**Comment by csoltenborn** [comment]
Closed due to inactivity.
