### ISSUE TITLE
Question: having console while running tests

### ISSUE THREAD

**Issue by dan31** [csoltenborn/GoogleTestAdapter#305]
My debugging flow is selecting a single test in Test Explorer and observing console output while stepping through breakpoints in my own code.
1) This output isn't available in `Output` → `Tests`.
2) Even if it was, I'd strongly prefer this output in a regular terminal window.

How is it possible to have 1 and/or 2?

**Comment by csoltenborn** [comment]
2 is not possible. For 1, make sure that the output is printed to the windows console if you run the test executable. If this is the case (and, obviously, if you have enabled option *Print test output*), your test output should appear in Output/Tests.

**Comment by dan31** [comment]
Thanks @csoltenborn. As an alternative for 2, https://code.google.com/archive/p/multi-console/downloads or similar could be used.

**Comment by csoltenborn** [comment]
In fact, GTA is written in C# (that library appears to be for C++)... But I'm probably not going to have time for that in the near future anyways, I fear. Pull requests welcome :-)

I will then close this issue.

**Comment by dan31** [comment]
@csoltenborn ah you mean to PR, TBH I may be close to this in the future 😊. As of now I meant to use such multi-console facility throughout your own code locally while debugging.

In fact this is more handy than one may think in a multi-monitor setup. Console trace is on the right, test list is on the left, code in the middle.

**Comment by csoltenborn** [comment]
@dan31 Ah, I see :-)

If you think that this is indeed worth sharing, there's also the option of enhancing the *SampleTests* solution for the sake of demonstrating this approach. Let me know if you are interested in this or have any other questions!
