### ISSUE TITLE
Fix Nuget package and add instructions 

### ISSUE THREAD

**Issue by L4ZZA** [csoltenborn/GoogleTestAdapter#312]
Adding googletestadapter from Nuget does not work. 
![image](https://user-images.githubusercontent.com/17835185/76787126-5408f680-67b0-11ea-8820-52d7c32fcabe.png)

You can't include the libraries in the C++ project after installing the package. The package does not include any header nor lib files and so it can't be used.
![image](https://user-images.githubusercontent.com/17835185/76787266-8d416680-67b0-11ea-8f02-f9834ac731bd.png)

**Comment by csoltenborn** [comment]
The GoogleTestAdapter NuGet package's purpose is not to provide gtest for your C++ projects, but only to teach VS/VsTestConsole.exe how to deal with gtest executables - it is a different way to install the GoogleTestAdapter extension (with some drawbacks as listed in the description). 

I guess you are looking for NuGet packages such as [this one](https://www.nuget.org/packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn/).

Let me know if I'm wrong...

**Comment by L4ZZA** [comment]
I am already using `Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn` but it doesn't include traits which are the main reason why I would use google test

**Comment by csoltenborn** [comment]
MS created these NuGet packages during the process of cloning my *Google Test Adapter* and releasing it as their *Test Adapter for Google Test*, and they decided to pack the "pure" gtest experience and not to include the custom macros for trait support that I created. If you want that changed, please ask [over here](https://github.com/microsoft/TestAdapterForGoogleTest).

However, it is rather simple to add support for traits: Just download [this file](https://raw.githubusercontent.com/csoltenborn/GoogleTestAdapter/master/GoogleTestAdapter/Core/Resources/GTA_Traits_1.8.0.h), add it to your solution, and include it into your test projects.
