### ISSUE TITLE
Slow debugging through GTA

### ISSUE THREAD

**Issue by bmo-Scape** [csoltenborn/GoogleTestAdapter#318]
I've been using GTA (from VSIX) for a while now with VS2019 16.4.5 and it has been working smoothly with my C++-projects.

However, after updating VS2019 to 16.7.5 and later 16.7.7, I noticed that the debugging through the "Test Explorer" (right-clicking and then selecting "Debug" on a specific test) has become extremely slow. Running a test of a normal release build is as fast as it has always been but debugging that same release build is easily 50-100 times slower than running the release test.

It seems that it is not a direct problem with VS2019 because debugging the entire test project (selecting that test project as the active projecting and then hitting F5), run times are comparable to when not debugging those tests.

If breaking the process that is being debugged through GTA, it is typically inside some allocation or deallocation of memory, sort of like it would be if "Heap profiling" is enabled under "Diagnostics Tools" (although it is disabled when I'm testing)

I've tried reinstalling the GTA plugin (as well as disabling the Qt plugin which gave me other problems) but that didn't change anything. Any other suggestion that I might try out?

**Comment by csoltenborn** [comment]
Thanks for the good problem description! However, I do not have any additional suggestions, I fear... Since nothing has changed with GTA, I'm assuming a VS regression (even if debugging via F5 works as desired). You could of course try the Microsoft flavor of the adapter (TAfGT), but I expect that this behaves the same way (otherwise please let me know).

I will leave this issue opened for some time in case there are more such problems or more insight.

**Comment by bmo-Scape** [comment]
Thanks for the quick response!

I tried the "Test Adapter for Google Test" and that one has the exact same behavior. A test that takes 18 seconds when choosing "Run" takes 9.2 minutes when choosing "Debug" 😢 

So I'll write a post on some VS2019-forum and put a link to it from here...

**Comment by bmo-Scape** [comment]
Created topic here:
[https://developercommunity2.visualstudio.com/t/Debugging-tests-through-the-test-explore/1246913](https://developercommunity2.visualstudio.com/t/Debugging-tests-through-the-test-explore/1246913)

Please upvote if you observe the same issue, thanks!

**Comment by csoltenborn** [comment]
Thanks for filing the bug report and letting me know!

**Comment by csoltenborn** [comment]
Closed due to inactivity - feel free to reopen if problem remains...
