### ISSUE TITLE
Could not find source location for test. with googletest/googlemock

### ISSUE THREAD

**Issue by sarukk** [csoltenborn/GoogleTestAdapter#319]
Hi,

We're using quite old version 1.7.0 [it's not up to me;)]. Currently we need to rebuild this library that was build in our env. sometime ago and it's working ok. 

But with the newly build libs, with VS 2017 we're getting Could not find source location for test warning and the test are not run. It's happening only when we execute test with vs test console and GTA test adapter. If we run the test executable directly they are running properly.

Any one had an idea what is the issue here apart from 'upgrade gtest'?

Thanks!

**Comment by csoltenborn** [comment]
See [trouble shooting section](https://github.com/csoltenborn/GoogleTestAdapter#no-source-locations-and-traits-are-found-for-my-tests) - let me know whether this helped.

**Comment by sarukk** [comment]
Hi Christian,

Thank you for your quick response. Unfortunately, non of the solutions worked.

1. pdb files are in the same directory.
2. /DEBUG:FULL is turned on on the test executable.
3. ParseSymbolInformation: True is showing on debug GTA output.

GTA is also reportng something like this: Found 138 test method symbols and 0 trait symbols in binary c:\w\NGDS\0.4\Toolbox-GTA\Toolbox\Build\Windows\Debug\ToolboxTest.exe, pdb c:\w\NGDS\0.4\Toolbox-GTA\Toolbox\Build\Windows\Debug\ToolboxTest.pdb

**Comment by csoltenborn** [comment]
2. would have been my guess... GTA prints out the command executed if debugging is enabled. What happens if you run that command in the printed directory?

Btw, my guess would also be that this is not related to gtest 1.7.0.

**Comment by sarukk** [comment]
If I run it in the printed directory the effect is the same. 

It may not be related to gtest 1.7.0, but, we have some old compiled gtest 1.7.0 that if used, it's working ok. When I use newly compiled binary, it behave like in this issue.

**Comment by csoltenborn** [comment]
Then the problem is probably related to that... internally, GTA just uses C#'s `Process` class to run the executable, and then parses the executable's output. If you are able to run the command as printed out and it works, then it will almost certainly also work within Visual Studio.

**Comment by csoltenborn** [comment]
Closing due to inactivty - feel free to reopen if you need more input.
