### ISSUE TITLE
Outdated links in wiki

### ISSUE THREAD

**Issue by milbrandt** [csoltenborn/GoogleTestAdapter#321]
On https://github.com/csoltenborn/GoogleTestAdapter/wiki/Google-Test,-VS-test-framework:-Documentation several links are no longer available or maintained:

- Overview -> 404
- General -> 404
- Configure unit tests by using a .runsettings file -> no longer updated
- Part 1 – Using Traits in the Unit Test Explorer -> 404

I discontinued to open the links.

**Comment by csoltenborn** [comment]
I have fixed the links on that page... Let me know if there are more broken links. Or even better, feel free to fix the links themselves - it's not that they were exactly hard to find, and it's a Wiki after all ;-)

**Comment by csoltenborn** [comment]
Closed due to inactivity...
