### ISSUE TITLE
"Object reference not set to an instance of an object" on VS launch

### ISSUE THREAD

**Issue by wrgrant** [csoltenborn/GoogleTestAdapter#323]
GTA version 0.18.0.1432

Get this error on startup of Visual Studio 16.9.2.

This causes initial test discovery to fail, as I I require a regex for test executable finding.

When I click the "Run All Tests" button in Test Explorer, the settings are loaded and the discovery works as expected.

```
Failed to configure settings for runsettings plugin 'GoogleTestAdapterSettings' as it threw following exception:
'Object reference not set to an instance of an object.'
Please contact the plugin author.
No settings file provided through env variable GTA_FALLBACK_SETTINGS
Warning: Using default settings.
```

**Comment by csoltenborn** [comment]
I have never heard of that problem, I fear... A workaround might be to set the mentioned env variable to the location of your settings file, but that's of course not nice at all. Sorry, don't know what to do about this - let's hope that it sorts itself out with an upcoming VS update... I will leave this open for some time in case others have the same problem.

**Comment by csoltenborn** [comment]
Just wanted to know whether you have in the meantime upgraded to e.g. VS 16.10, and whether you are still seeing this issue...

**Comment by wrgrant** [comment]
Sorry, have not and not working on this project anymore. Thanks.

**Comment by csoltenborn** [comment]
Thanks for letting me know!
