### ISSUE TITLE
Test discovery fails when using vcpkg Autolink 

### ISSUE THREAD

**Issue by monamimani** [csoltenborn/GoogleTestAdapter#334]
I am using google test from vcpkg. In the project property in the vcpkg section there is a Use AutoLink feature when enable ( and not specifying the lib in the linker inputs the test fails to be discovered.

**Comment by csoltenborn** [comment]
Sorry for answering late... I have no experience whatsoever with vcpkg (I'm not living in the C++ world any more). Please try to run your test executable from the console and check whether test discovery works that way (see trouble shootig section) - if it doesn't, this isn't anything related to GTA.

**Comment by monamimani** [comment]
Actually I think there is no. Issue. I didn't know that there was a 'manual-link' feature to vcpkg. So libraries copy their lib to the manual-link to prevent duplicate symbol with other libs, for example main.

**Comment by RampantDespair** [comment]
@monamimani 
Hey there,
I'm currently facing this exact problem, do you recall how you resolved your issue?
I don't see a `Manual Link` option in the vcpkg settings tab:

<img width="566" height="358" alt="Image" src="https://github.com/user-attachments/assets/64fda327-2189-40fb-9848-0d6b8ee9d552" />
