### ISSUE TITLE
GTest report generation - Question

### ISSUE THREAD

**Issue by amaljesudas** [csoltenborn/GoogleTestAdapter#344]
How can we generate the google test report xml if we are running tests from the Visual Studio test explorer?
Right now I am able to run tests from test explore but report xml does not get generated.
It gets generated only when I run the generated google test binary in command prompt;

**Comment by csoltenborn** [comment]
Have you tried passing the according parameter (`--gtest_output="xml:<file name>"`) using the option *Additional test execution parameters*?

**Comment by csoltenborn** [comment]
Closed due to inactivity.
