### ISSUE TITLE
Typed tests do not run

### ISSUE THREAD

**Issue by travnick** [csoltenborn/GoogleTestAdapter#346]
I'm using 
```
Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.3.2
Test Adapter for Gootle Test 0.17.0.9 (from VS extensions gallery)
```

I have about 7k tests and just realized that 38 of them are not ran at all (they are shown as greyed out). Furthermore, I'm able to push "run" on such test, but it ends up as "test was not run".

All tests run successfully in command line.

I have no idea how to provide more information.

Here is a sample test that does not run:
```
template <typename T>
class Logger_LogEntry: public ::testing::Test
{
protected:
    /// My code here
};

using TestTypes = ::testing::Types<char, wchar_t>;
TYPED_TEST_CASE(Logger_LogEntry, TestTypes);

TYPED_TEST(Logger_LogEntry,  ImplementsEntryToStream)
{
    /// My code here
}
```

**Comment by csoltenborn** [comment]
This is Google Test Adapter, but you are using Test Adapter für Google Test, the Microsoft clone of my adapter. Please refer to Microsoft for support...
