### ISSUE TITLE
Provide a better defined software license

### ISSUE THREAD

**Issue by peterbudai** [csoltenborn/GoogleTestAdapter#40]
Not having a well defined software license discourages contributions.

There is a [license on the VS Gallery page](https://visualstudiogallery.msdn.microsoft.com/site/94c02701-8043-4851-8458-34f137d10874/eula?licenseType=None), and it can be found [within the repository](https://github.com/csoltenborn/GoogleTestAdapter/blob/master/GoogleTestAdapter/VsPackage/Resources/ApacheLicense.txt) as well, but it would be beneficial if the license text would appear in the standard location (a file named LICENSE) and with the placeholder snippets replaced with actual values.

**Comment by csoltenborn** [comment]
Thanks for pointing out the missing placeholder replacements - I must admit that I hadn't seen them. I will fix that soon.

What standard location do you mean? Do you expect that LICENSE file to sit in the repository root (or the solution roots, or the VSIX)? Is the file just named LICENSE, without any suffix? Is there any standard you can point to where I can learn about that stuff? Again, thanks in advance...

**Comment by peterbudai** [comment]
Yes, I meant the LICENSE file in the repository roots.
For guidelines and best practices you may refer to this documentation:
https://help.github.com/articles/open-source-licensing/

**Comment by csoltenborn** [comment]
Thanks for the info, I made according adjustments to the repository.
