### ISSUE TITLE
v0.5.0.340 is broken in VS2013

### ISSUE THREAD

**Issue by kornman00** [csoltenborn/GoogleTestAdapter#42]
After updating through VS and then downloading the .visx from here directly, I get the following error on startup/settings page. It would appear the VS2013 installation is built with references to the VS2015 assemblies? 2013 is v12, and I believe 2015 is v14, right?

`
  <entry>
    <record>939</record>
    <time>2016/03/26 20:47:28.608</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [GoogleTestExtensionOptionsPage]</description>
    <guid>{E7C90FCB-0943-4908-9AE8-3B6A9D22EC9E}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.ComponentModelHost, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>940</record>
    <time>2016/03/26 20:47:28.608</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [GoogleTestExtensionOptionsPage]</description>
    <guid>{E7C90FCB-0943-4908-9AE8-3B6A9D22EC9E}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.ComponentModelHost, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
`

**Comment by csoltenborn** [comment]
That's bad - looks like a have indeed messed up the references. It's a pain in the bud to maintain an extension for more than one VS version, and I don't have a VS2013 at hand, so sorry for that.

Can you please try on VS2013 whether [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.5.0.341/artifacts) fixes the issue, and whether the little toolbar we added is still available and working properly? Buttons should be enabled when a solution is opened, and should show (and change) the according settings in VS's options... I will than quickly release that fixed version. Thanks in advance.

**Comment by kornman00** [comment]
Just tested it: that version doesn't throw the exception, allows me to view/change the settings again, and has the toolbar available (which also appears to be working). Seems shippable :+1:

**Comment by csoltenborn** [comment]
Thanks a lot! :-)
