### ISSUE TITLE
Parameters ared set for visual studio, not per projects

### ISSUE THREAD

**Issue by tbuffry** [csoltenborn/GoogleTestAdapter#47]
I have two solutions, one where all gtests are following the same rule, with 10 gtests project, it works perfectly.

The second solution is a mix of mess, with gtests initializing web servers, making them crash during test discovery with lots of popups, but I can't disable them easily. So if you could associate the parameters of GTA with a sln, it would be perfect for me ( maybe by loading a specific file for config )
$(SolutionDir)\gta.config ?

**Comment by jgefele** [comment]
Hi @tbuffry,

it is possible to configure the test runner per **solution** (.sln), but not per **project** (.vcxproj). But as I understand this already solves your problem. Please have a look at [step 2 of GoogleTestAdapter > Configuration](https://github.com/csoltenborn/GoogleTestAdapter#configuration). Feel free to reopen the issue if you still have any questions.

Cheers,
Jonas

**Comment by tbuffry** [comment]
Perfect, I did not found the option, and did not thought of reading the home page again ... maybe this would raise a lower than minor usability issue, btw thanks for the reply, this was really helpful.
