### ISSUE TITLE
Tests can't execute and the process is hanged

### ISSUE THREAD

**Issue by syedbokhari** [csoltenborn/GoogleTestAdapter#51]
I'm new to GTA and GoogleTest and have just set up the add-in with my VS2015. Tests are discovered and visible in the Test Explorer. 
But as I build the project, test execution is started but never stops.

I've debug enabled in GTA > General and see following in the test execution console. 

> ------ Discover test started ------
C:\Dev\GTTest1\Debug\GTTest.exe matches regex '[Tt]est[s]?\.exe'

![image](https://cloud.githubusercontent.com/assets/2768528/15099598/19e165d4-1573-11e6-8b3c-ba3069b38d86.png)

And I've to kill the process exe from the Task Manager. 

I've only one CPP file for test that looks like following:

`
#include "stdafx.h"
#include <gtest/gtest.h>
#include <iostream>

using namespace std;

int Factorial(int n) {
	if (n > 0) {
		return n*Factorial(n - 1);
	}
	return 1;
}

int main(int argc, char **argv) {
	::testing::InitGoogleTest(&argc, argv);
	int testResult =  RUN_ALL_TESTS();
	getchar();
	return testResult;
}

// Tests factorial of 0.
TEST(FactorialTest, HandlesZeroInput) {
	EXPECT_EQ(1, Factorial(0));
}

// Tests factorial of positive numbers.
TEST(FactorialTest, HandlesPositiveInput) {
	EXPECT_EQ(1, Factorial(1));
	EXPECT_EQ(2, Factorial(2));
	EXPECT_EQ(24, Factorial(4));
	EXPECT_EQ(40320, Factorial(8));
}
`

**Comment by syedbokhari** [comment]
I believe, the issue was with the change in the project name and duplicate configurations. I just cleaned my Debug folder and it's now working perfectly.

**Comment by csoltenborn** [comment]
Good to hear - happy testing!
