### ISSUE TITLE
Breaks test_all project in Windows Caffe for VS 2013

### ISSUE THREAD

**Issue by KevinLucidyne** [csoltenborn/GoogleTestAdapter#57]
If you download and compile this code on a virgin copy of VS 2013:

`https://github.com/BVLC/caffe/tree/windows`

All the tests compile and run.  But if you install GoogleTestAdapter, it makes changes that cause about 200 compilation errors in gtest-all.cpp and other files, mainly having to do with the String definition.

**Comment by csoltenborn** [comment]
Sorry, I do not understand - do you mean that *installing* GoogleTestAdapter breaks compilation of the project? I don't know how that could be possible, since GTA does not at all change anything with that respect. Or have you included our [GTA_Traits.h](https://raw.githubusercontent.com/csoltenborn/GoogleTestAdapter/master/GoogleTestAdapter/Core/Resources/GTA_Traits.h) into that code, and that breaks it?

**Comment by KevinLucidyne** [comment]
Yes, installing GTA breaks compilation of test_all on VS 2013.  Try it 
and see.

**Comment by csoltenborn** [comment]
Well, I do not have a VS2013 at hand, but we will see what we can do. Can you please in the meantime provide some more info, e.g. the compiler output?

**Comment by KevinLucidyne** [comment]
Hi Christian,

I tried to reproduce the error from scratch:

0. Start with clean source code from a previous check in.

1. Download and run the VSIX Installer from

https://github.com/csoltenborn/GoogleTestAdapter/releases/download/v0.6.0/GoogleTestAdapter-0.6.0.vsix

2. Rebuild the test_all project

3. Test Explorer | Run all

This time the tests successfully compiled.  I think the problem may be 
that the last time I installed GTA, I had VS 2013 open and the 
configuration files were corrupted.  That's just a guess though.

I'm currently at the Discover test phase but the Test Explorer doesn't 
find any tests.  Any suggestions?

Thank you very much.

Kind regards,
Kevin

**Comment by KevinLucidyne** [comment]
Changing the test executable regex in options took care of the discovery.

Thank you for your help!

Kind regards,
Kevin

**Comment by KevinLucidyne** [comment]
How do you set the working (current) directory for tests in GTA?  I'm running the following through GTA and the test isn't finding the input files in GTA but is finding the input files if I just run test_all.exe directly.

```
Running 2005 tests...
Executing command 'C:\Users\Kevin\dev\IPSight\caffe-windows-lenet-2106-06-22\Build\x64\Debug\test_all.exe --gtest_output="xml:C:\Users\Kevin\AppData\Local\Temp\tmp5AED.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=1 --gtest_shuffle'.
>>>>>>>>>>>>>>> Output of command 'C:\Users\Kevin\dev\IPSight\caffe-windows-lenet-2106-06-22\Build\x64\Debug\test_all.exe --gtest_output="xml:C:\Users\Kevin\AppData\Local\Temp\tmp5AED.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=1 --gtest_shuffle'
Cuda number of devices: 1
Current device id: 0
Current device name: Quadro M1000M
Note: Randomizing tests' orders with a seed of 36388 .
[==========] Running 2005 tests from 269 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from NesterovSolverTest/2, where TypeParam = struct caffe::GPUDevice<float>
[ RUN      ] NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithMomentum
<<<<<<<<<<<<<<< End of Output
Warning: Test result file C:\Users\Kevin\AppData\Local\Temp\tmp5AED.tmp could not be parsed (completely) - your test has probably crashed. Exception message: Root element is missing.
Thread 0 took 00:00:11.8286045
Test execution completed.
========== Run test finished: 2005 run (0:00:17.9562583) ==========


```

**Comment by csoltenborn** [comment]
Ok, glad to know that you got it (basically) working.

We use the test executable's directory as the working directory when running that executable. However, the output you posted doesn't say anything about missing input files - instead it seems the test executable (i.e., test `NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithMomentum`) seems to have crashed (that warning is produced by our code and says that we can't read the xml test result file which should have been created by the test executable). Have you run the tests from command line (is that what you mean with *run directly*)?

Maybe try to set the test project as your solution's startup project, put a breakpoint at that test's code, and debug the test as you would debug a normal C++ program...

**Comment by csoltenborn** [comment]
@KevinLucidyne Since you haven't come back on this for a while, I assume you have resolved your remaining problems, so I'm closing this issue. Feel free to open a new one (or add comments to this one) if you still encounter any problems...

**Comment by KevinLucidyne** [comment]
Is this fix in the last release?

**Comment by csoltenborn** [comment]
Which fix do you mean? This issue was apparently invalid... See the [release notes](https://github.com/csoltenborn/GoogleTestAdapter/releases) for all fixes which went into the last release.

**Comment by KevinLucidyne** [comment]
That the test failure doesn't put the failed assertion into Test Explorer or in the Output window.
```
Running 2005 tests...
Executing command 'C:\Users\Kevin\dev\IPSight\caffe-windows-lenet-2106-06-22\Build\x64\Debug\test_all.exe --gtest_output="xml:C:\Users\Kevin\AppData\Local\Temp\tmp5AED.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=1 --gtest_shuffle'.
>>>>>>>>>>>>>>> Output of command 'C:\Users\Kevin\dev\IPSight\caffe-windows-lenet-2106-06-22\Build\x64\Debug\test_all.exe --gtest_output="xml:C:\Users\Kevin\AppData\Local\Temp\tmp5AED.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=1 --gtest_shuffle'
Cuda number of devices: 1
Current device id: 0
Current device name: Quadro M1000M
Note: Randomizing tests' orders with a seed of 36388 .
[==========] Running 2005 tests from 269 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from NesterovSolverTest/2, where TypeParam = struct caffe::GPUDevice<float>
[ RUN      ] NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithMomentum
<<<<<<<<<<<<<<< End of Output
Warning: Test result file C:\Users\Kevin\AppData\Local\Temp\tmp5AED.tmp could not be parsed (completely) - your test has probably crashed. Exception message: Root element is missing.
Thread 0 took 00:00:11.8286045
Test execution completed.
========== Run test finished: 2005 run (0:00:17.9562583) ==========
```

**Comment by csoltenborn** [comment]
This is not a failed assertion! If it was, there would be a line starting `FAILED`below that `RUN` line. The test `NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithMomentum` has crashed so hard that Google Test could not catch that crash. This test should be shown as failed in the test explorer, and its message should say something like *This test has probably crashed*.

The rule is that if a `RUN` isn't followed by a `FAILED` or a `PASSED` line, but by the `<<< End of Output` line (and maybe some output of the test before that line, produced before it crashed), the test has crashed.

And please, do not use the randomize test order option unless you are sure that your test suite indeed supports that kind of execution (or you want to find tests that break that kind of execution for the sake of improving your test suite)! From the [Google Test docs](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md): `You can specify the --gtest_shuffle flag (or set the GTEST_SHUFFLE environment variable to 1) to run the tests in a program in a random order. This helps to reveal bad dependencies between tests.`

>

**Comment by KevinLucidyne** [comment]
Shuffle is off.  That was an old output. :-) Same issue without.
