### ISSUE TITLE
Logging stops working if host process is being reused

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#6]
* Enable Test>Test Settings>Keep Test Execution Engine Running
* Enable Test>Test Settings>Default Processor Architecture>x64<br>
   (for x86 the "keep ... running" setting is a no-op.)
* Run tests multiple times.

After the first run there will be no more test output.

* Disable Test>Test Settings>Keep Test Execution Engine Running
* Kill the execution engine process
* Run tests multiple times.

All runs have test output.

Probably this is because IMessageLogger is being reused between multiple calls into GTA.

This problem is more important for VS2013 because here the execution engine is being reused by default for x86.

**Comment by csoltenborn** [comment]
This might already be fixed by commit 0fb09f3f, since the TestEnvironment is now instantiated freshly for every test run, using the current IMessageLogger instance. Need to try, though...

**Comment by jgefele** [comment]
Yep. It has been fixed by that commit and now has been merged into master.
