### ISSUE TITLE
Test adapter for VSTest

### ISSUE THREAD

**Issue by DavizOWNS** [csoltenborn/GoogleTestAdapter#64]
Could you provide test adapter for VSTest so that I could use this when building in Visual Studio Online. I can run exe that runs tests as part of build but I do not get that nice reports and graphs about tests which would be amazing.

**Comment by csoltenborn** [comment]
I guess you have already closed the issue again because you have figured out how to do this - if this is true, would you mind to share?

Despite that, note that we have plans to provide GTA via Nuget, which will make scenarios like yours easier to handle, but that will probably take some time.

**Comment by DavizOWNS** [comment]
I have just followed #21 (did not notice that earlier) and everything now works just fine. Just struggling with code coverage setup :/
