### ISSUE TITLE
PathExtention should manage placeholder like AdditionalTestExecutionParam

### ISSUE THREAD

**Issue by cyrilbesse** [csoltenborn/GoogleTestAdapter#66]
Hi,

In *.gta.runsettings file (or via the  option windows), I need to add relative paths by rapport to the executable location in the PATH execution.

I propose to manage this syntax, in *.gta.runsettings:
```
<GoogleTestAdapter>
    <PathExtension>$(ExecutableDir)\..</PathExtension>
</GoogleTestAdapter>
```
with $(ExecutableDir) - executable directory containing the tests

Regards
Cyril

**Comment by csoltenborn** [comment]
Great suggestion, and rather easy to implement! Feel free to download the vsix produced by [this build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.7.0.468) if you want to test the enhancement or if you need it urgently...

**Comment by cyrilbesse** [comment]
Hi,
Thanks for your reactivity. 
Test and approved

**Comment by csoltenborn** [comment]
Sweet - will not take too long until it's going to be released...
