### ISSUE TITLE
Test Explorer stops on test failure

### ISSUE THREAD

**Issue by KevinLucidyne** [csoltenborn/GoogleTestAdapter#67]
Same setup as Issue #57.   When a test fails, the whole Test Explorer stops.  I want Test Explorer to run all the way through and then go back to fix all the tests that break.  Just like MSTest.

**Comment by csoltenborn** [comment]
We have two cases here:
* If a test crashes hard, the remaining tests of the containing test executable can not be executed - there's nothing we can do about that. The test explorer should howver (as you know) point to the crashing test.
* If a test just fails, the default behavior is exactly as you want. Have you by any chance enabled the *Break on failure* or disabled the *Catch exceptions* option?

**Comment by KevinLucidyne** [comment]
That was the problem. "Break on Failure." Thanks.
