### ISSUE TITLE
Sign the resulting VSIX

### ISSUE THREAD

**Issue by csoltenborn** [csoltenborn/GoogleTestAdapter#7]

**Comment by csoltenborn** [comment]
We need a provider for a code signing certificate (for free) - any suggestions welcome...

**Comment by csoltenborn** [comment]
There do not seem to be free code signing certificates. I found some cheap ones, but we are not going to spend money on this as a matter of principle (we do spend our valuable time :-) ).

If anybody wants to contribute a certificate for Google Test Adapter, contact us! Otherwise, signing is not going to happen...

**Comment by csware** [comment]
Cheap code sign certificates ($14) for open source developers are available from Certum.pl

**Comment by LukaszMendakiewicz** [comment]
Please note that the Microsoft distribution of the adapter is fully signed. I am not sure if you want to consider this "Done" with that.

**Comment by csoltenborn** [comment]
Hm, that's true - sounds good to me :-)
