### ISSUE TITLE
Test explorer progress bar always busy

### ISSUE THREAD

**Issue by sweetim** [csoltenborn/GoogleTestAdapter#84]
When the discover test started, at the output tab, the console shows it got stuck in `... matches regex '[Tt]est[s]?\.exe'`, 
and the Visual Studio test explorer stuck in progress mode.

May I know how can I fixed this problem?

**Comment by csoltenborn** [comment]
Have you checked our trouble shooting section? In particular, are you able to run your test executable on the console? My first guess would be that your test executable doesn't return if called with the `--gtest_list_tests` command line option...

**Comment by sweetim** [comment]
@csoltenborn yes you are right, my test return does not `return` that why the test gets hang...
maybe in the future, the adapter should have a timeout rather than get stuck forever?

**Comment by csoltenborn** [comment]
Timeout is a good idea, we will consider this for future releases. Glad that you found the problem!
