### ISSUE TITLE
Publishing test results through TFS 2015

### ISSUE THREAD

**Issue by dishmal** [csoltenborn/GoogleTestAdapter#85]
I am able to use vstest.console to execut the tests successfully on my TFS 2015 build.  The issue I have is that they don't show up in the build stats.  I tried using the vstest publish build task and use the xunit style to publish the test data (as well as vstest style) but neither results in showing that any tests were actually ran.  Thoughts?

**Comment by csoltenborn** [comment]
Not really, but we are executing Google Tests with TFS 2015 and our adapter at work - I haven't set it up, but I will check the configuration mid of next week if you haven't figured out the cause for the problem by then.

@sirotnikov Can you maybe in the meantime jump in and provide some info on how to properly set up TFS with our adapter?

**Comment by sirotnikov** [comment]
I'm on vacation from work so I'll talk to the CI people next week.
I think we ended up putting the test binaries in a specific path and directing the build controller to the binaries. Then we manually ran the tests in vstest console, and then published the results using mstest to the relevant build.

We are however in the process of ditching TFS in favor of GitHub and jenkins, so I'll try to rescue the config before it's offline.

**Comment by sirotnikov** [comment]
It was however achieved mostly using scripts and not the built-in tasks

**Comment by csoltenborn** [comment]
Thanks already for your fast response!

**Comment by dishmal** [comment]
I appreciate the responses.  I'm using a command prompt through TFS to run vstest.console.exe.  The problem I'm seeing is controlling where the file that outputs the info about the test run gets placed.  I tried using the settings file and passing that in as an argument, but it didn't write any file to the location I specified.  I appreciate the help and will wait for you to be back in your office to determine how you had it set up.  Once I see how you did it, I'll submit an updated build task for the publish test run and vstest that includes google test.  I'm surprised they don't already have it.

**Comment by sirotnikov** [comment]
Ok I logged in remotely to try and help.

This exists in the **.runsettings** file:

    <?xml version="1.0" encoding="utf-8"?>
    
    <RunSettings>
        <RunConfiguration>
            
            <ResultsDirectory>.\TestResults</ResultsDirectory>
        </RunConfiguration>
    ...

The call to vstest is in the spirit of:

    cmd /c "vstest.console.exe" 
       "%TEST_BINARY%"
        /TestAdapterPath:"%ADAPTER_PATH%" // not sure if this is necessary or even used.
        /Logger:trx 
        /EnableCodeCoverage 
        /Settings:"foo.runsettings" 
        /inIsolation 
        /Platform:x64

then get the file name, you can use 
**GetChildItem** on "*%SOURCE%\TestResults*" with a *.trx parameter and then use the **Name** property on the resulting list to get the filename.

then publish using

    cmd /c  "$MSTEST_PATH\MSTEST.exe 
        /publish:"YOUR_TFS_COLLECTION_URI" 
        /publishresultsfile:"%SOURCE%\TestResults\%TRX_FILE_NAME%" 
        /publishbuild:"YOUR_BUILD_NUMBER" //this could be passed as a parameter or env variable
        /teamproject:"YOUR_PROJECT_NAME" 
        /platform:"x64" 
        /flavor:"Debug" //(or "Release)

see: https://msdn.microsoft.com/en-us/library/ms243151.aspx?f=255&MSPPError=-2147217396

**Comment by sirotnikov** [comment]
What I think helped our tests being run is when we placed the test adapter in a path that was specified to the build agent, as per directions in https://msdn.microsoft.com/en-us/library/ms253138(v=vs.120).aspx?f=255&mspperror=-2147217396#Anchor_6

I can't help further since most the work was completed by the release and CI engineer.

@csoltenborn what I think would be great is GTA leverages the fact TFS should automatically pick up binaries for adapters that are provided as NuGet packages. I'm not very familiar with how it works, but I think it automatically follows project packages.

**Comment by csoltenborn** [comment]
@sirotnikov We have a NuGet package on our list already (see #77) - in fact you can already try the one provided with [this build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.8.0.565), but your mileage might vary ( @dishmal this could also be an option for you, but it's not tested despite the automatic tests, which do not test things like VS UI integration or debugging of tests).

However, we will certainly also want to provide documentation on how to set up TFS, I guess. Your explanations will cetainly be a good starting point for this (feel free to provide a pull request :-) ).

Btw: we still have #21 on our list - this will eventually happen. Just to let you know ;-)

**Comment by csoltenborn** [comment]
I have just looked up the build step for running Google Tests on our build server. Note that our build server has an own installation of VS (which is used for building), and that our test adapter is installed into that VS instance (hence the option `/UseVsixExtensions:true`).

Here's a screenshot of our settings. As always, please let us know your results - I will update our docs accordingly.

![image](https://cloud.githubusercontent.com/assets/352576/19960276/1a0d6966-a1ac-11e6-80f9-2ca931409ea2.png)

**Comment by csoltenborn** [comment]
Closed because of inactivity - feel free to reopen if you still have problems, or if you want to provide information on the final, working setup you are using.
