### ISSUE TITLE
Can't run a single test from Test Explorer.

### ISSUE THREAD

**Issue by ftrofin** [csoltenborn/GoogleTestAdapter#87]
First I want to thank the developers for creating and maintaining this project. Great job! I want to report an issue which I am not sure if it is real or is just "operator error" :-). After fiddling for a while with GTA to discover my tests (I did not realize that it wants a separate executable) I managed to have my tests discovered. The tests are implemented in a DLL and they are showing up in the Test Explorer. However, when I right click on any of them and select "Run selected tests" or "Debug selected tests" invariably I get the same result (see attached debug output). Please let me know how can I fix this (or workaround it). Thx!
[GTA debug output when running single test.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/593576/GTA.debug.output.when.running.single.test.txt)

**Comment by csoltenborn** [comment]
Thanks for your kind words! :-)

I've looked at your test output, and it appears that the test framework is not able to launch a process with a debugged attacher. However, the error should be different when running the test then (i.e., the attached output seems to be one from debugging your test). Can you please double-check this, and attached the output from running your test if it's indeed different?

Despite that: Are you able to run your test executable `d:\MyTest\\lib\win\debug\64\runtestapp.exe` on the command line?

**Comment by ftrofin** [comment]
Thanks for the quick reply. The output I attached is when I right-click a test and select "Run Selected Test". I turned on the debug info in the GTA options in VS. See attached screenshot.
<img width="345" alt="gta options screenshot" src="https://cloud.githubusercontent.com/assets/8718388/20363137/ff5a8d5a-abf2-11e6-85d3-6b8f0f82e3a4.png">

Yes, now I am able to launch/debug  my executable from VS and it will run all my tests. (Initially I had a problem where the tests would not run and it will give out a cryptic error because some dependency DLLs were not found. I can open a separate ticket with the suggestion to improve the error message in that case because it was very confusing - I did not understand what was happening. Only when I tried to run my executable directly I could see the error message: "One or more Dlls are missing".

I think you should output more (helpful) diagnostic info when you encounter an error during execution. For example in this case if you look at the top of the stack:

ERROR: Exception while running tests: System.ArgumentException: Process with an Id of -1 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at GoogleTestAdapter.Helpers.TestProcessLauncher.LaunchProcessWithDebuggerAttached(String workingDirectory, String command, String param, Boolean printTestOutput, IDebuggedProcessLauncher handle)

I presume that the directory is wrong or the executable is not present there. Should be easy to check for that and output a more helpful error (or debug message). Please let me know if I can help with anything else and thanks again for your help!

**Comment by ftrofin** [comment]
I have some more info: I added a new test to one of the files and VS did not discovered it automatically (did not show up automatically in Test Explorer). So I clicked "Run all" link in the Test Explorer pane. I got the attached error.
[GTA debug output when running all tests.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/596370/GTA.debug.output.when.running.all.tests.txt)

This seems similar and it complains about a directory name being invalid. Hope this helps.

**Comment by csoltenborn** [comment]
Thanks for your suggestions and the added information! I agree that our error messages could be improved at several places (feel free to open the issue on that one), but also note that you apparently haven't read our [trouble shooting section](https://github.com/csoltenborn/GoogleTestAdapter#trouble_shooting) (which suggests to run the test executable from command line when having problems).

The problem with your initial error is as follows: We just call into VS API to launch the executable with an attached debugger, and we get the process's id as return value (-1 in your case) - that's it. Thus, there is no way of telling that there are DLLs missing or something (but we could of course catch the exception, print out the exception message, and point to our trouble shooting section ;-) ). Plus, we also receive the test executables from the VS API, which probably means that there's no sense in checking whether the executables do exist (we could check for existence of the user provided settings, though - see below).

The problem of your last comment is easily solved: We do not support a placeholder `$(OutDir)`, thus the `invalid directory` message. Please refer to the options' descriptions for available placeholders!

**Comment by ftrofin** [comment]
Thank you Christian for quickly diagnosing the issue with $(OutDir). Doh!
One more thing :-) : in the log attached to my initial post, you can see messages like: "Warning: Could not find source location for test utestFixtureExample.TestSuccess1". I noticed that this means that I can't use the Test Explorer to go to a failed test quickly by double clicking it (doesn't know where the source is). I was wondering what can be the issue here and how we can fix it.

Thanks!

**Comment by csoltenborn** [comment]
You're welcome! Your assumption is right - we were not able to find source locations within the pdb belonging to the executable, thus, links are not available. Have you checked the project settings as described in the 5th bullet point of our trouble shooting section? If this isn't the problem, I guess I need more information (e.g., are there any tests in your executable where source file locations are found?) or even the solution (can you attach it to this issue? I will then have a look at the weekend)...

**Comment by ftrofin** [comment]
Christian, I checked and I do have the correct settings as recommended in the troubleshooting section (linker debug info, etc). I think I uncovered a new issue which is even more upsetting: I can't use the "Go to definition" shortcut from the context menu in VS when I right-click a function. Also, all other symbol-related functionality seems broken ("Generate graph of include files" brings up the attached error dialog.)

![generate graph of include files error](https://cloud.githubusercontent.com/assets/8718388/20444596/846b91b2-ad86-11e6-9ac6-88c277625ac4.png)

Initially I thought this was a VS 2015 issue, but now I think it might have something to do with the plugin. The reason is, when I say "Run all tests" I now get the following output in the Tests log:

TestMethodResolver 'VsTestMethodResolver' threw following exception:
'The solution's source code database may not have been opened.  Please make sure the solution is not open in another copy of Visual Studio, and that its database file is not read only.'
Please contact the plugin author.

Notice that this message is very similar to the one in the attached screenshot. Does the plugin open the PDB file with exclusive ownership access? I certainly don't have multiple VS instances running and I restarted the machine and VS multiple times but the error is the same.

Thanks!

**Comment by csoltenborn** [comment]
We are indeed using the pdb for finding source locations, but 1) this only happens for a short period of time (protected by a `using` clause - see #46 or [this commit](https://github.com/csoltenborn/GoogleTestAdapter/commit/c45b618ad01bc81a61b56eda9b38628f39e50d79)) and 2) the pdb does not contain the "solution's source code", but information about the relation of an executable and the source code it was compiled from.

My guess would be that either your solution is broken or that you have [this problem](http://stackoverflow.com/questions/14716068/vs2010-depends-on-sql-server-compact-3-5-for-intellisense), but it's hard to say without access to that solution.

**Comment by ftrofin** [comment]
Thank you Christian for the clarification, I'll try re-installing my VS to see if this issue goes away. I'll close this issue now.

**Comment by csoltenborn** [comment]
I would recommend first deleting that `.sdf` file - maybe that fixes the problem already...
