### ISSUE TITLE
Support for VS2012

### ISSUE THREAD

**Issue by jgefele** [csoltenborn/GoogleTestAdapter#9]
VS2012 update 4 is already tested.
VS2012 update 1-3 work run, too.
VS2012 w/o update doesn't work due to missing traits support.

**Comment by Herculis8** [comment]
How to make it run with VS2012? I have no internet connection. By running the .vsix it does not allow to install it.
Thanks in advance!

**Comment by csoltenborn** [comment]
Sorry, we do not have a release yet which runs on VS 2012. Jonas only tested if it would work in general (which it does), but it's cumbersome and not easy to come up with proper support for all VS versions. We will tackle this eventually, but we cannot provide a date or something - sorry for that...

**Comment by jgefele** [comment]
Hi @Herculis8,

I don't know if GoogleTestRunner still works with Visual Studio 2012. I didn't try for some time. Maybe we now use some API which isn't supported by Visual Studio 2012.

If you want to give it a try, follow these steps:

1. download the VSIX
1. rename it to ``*.zip``
1. extract ``extension.vsixmanifest``
1. replace all occurences of ``Version="[12.0,14.0]"`` by ``Version="[11.0,14.0]"``
1. add the modified ``extension.vsixmanifest`` back into the ``*.zip``
1. rename to the original file name
1. install

Please let us know your findings.

Cheers,
Jonas

**Comment by csoltenborn** [comment]
Support for VS2015 update 1 and above has been added. VS 2015 without updates is not supported because of lack of traits and solution directory support.
