### ISSUE TITLE
Discovering test after project reload or after creation does not work

### ISSUE THREAD

**Issue by sephirostoy** [csoltenborn/GoogleTestAdapter#92]
Hello,

I'm using Google Test Adapter with Visual Studio 2015 update 3.
When I reload a project which contains unit tests (not the whole solution) and I build the project, its tests are not discovered in the test explorer.
The same happens for newly written tests.

In both case, I have to close and reopen the solution, and then they appear in the test explorer.

**Comment by csoltenborn** [comment]
Hi and thanks for your bug report! Can you please do two things:
* Run the resulting test executable on the command line with option `--gtest_list_tests` (if this does not work properly, our adapter has no chance to discover your tests correctly) - see also our trouble shooting section
* Enable *Debug Mode* in the GTA settings and post the resulting debug output

In fact, I do not expect something special to happen because you wrote that re-opening the solution fixes the problem, but I'd like to rule out problems we have quite often seen.

**Comment by sephirostoy** [comment]
Hi,

thanks for the quick reply. Using the command line option display my tests correctly. Actually, I think the problem comes from the discovery which is not triggered when I recompile my unit test projects.
Here is the hierarchy of my output folder:
`./LauncherTest.exe`
`./addonsTest/Library1Test.dll`
`./addonsTest/Library2Test.dll`

`LauncherTest.exe` does not contains test itself, it's just used to launch tests contained inside the subfolder `./addonsTest/`. And during development process, I recompile only the dlls inside `./addonsTest/`.

In the option, I've set the path extension to: `$(ExecutableDir);$(ExecutableDir)/addonsTest;`.
But I guess I have to also set the regex for test discovery, right?

**Comment by csoltenborn** [comment]
It depends... In debug mode, the test adapter should tell you which executables have been sent by VS, and which of those executables are matched by the configured regex. If your executable is listed, but does not match the regex, than that's what you have to fix. However, it sounds like test discovery is not triggered for your executable if you only compile the dlls - if this is the case (i.e., if your executable is not listed in debug mode), than there's probably nothing we can do about it...

Let us know your results!

**Comment by sephirostoy** [comment]
So when I open my solution, at the first test load, in debug mode, I see that my .exe is correctly found and it add test cases from other dlls.
But when I recompile only the dlls, it does nothing. I have to recompile my exe so that the discovery is triggered again.

Is it possible to add such triggers in GTA, to detect that one of the dll has been recompiled; or even a simple refresh button to trigger it manually? Or is it completely managed by the VS test framework as a black box.

**Comment by csoltenborn** [comment]
I fear this is not possible - we just get the executables from VS, and there is no way to trigger discovery on our own (at least no way we are aware of) - even if we would add a refresh button and trigger our code (which would in general be possible), we wouldn't have any way to report discovered tests to VS (the according object of type `ITestCaseDiscoverySink` is passed to our framework when VS starts test discovery after a build has completed).

Not sure if this is an option for you, but I think the problem could be solved by adding a dependency from the project resulting in the executable to the projects resulting in the dlls such that the former project is compiled whenever the latter projects are...

**Comment by sephirostoy** [comment]
I have found a workaround for my case: I can run a post build command line which "touch" the exe.
In this case, Visual triggers the discovery since the modified time of the exe has changed since last time.
I think I can close the issue. As far as I understand, the problem comes from the lack of features in the Test API on Visual Studio side.
Anyway, thanks you very much for your quick support.

**Comment by csoltenborn** [comment]
You're welcome, and thanks for letting us know! I will probably add that hint to our docs...
