### ISSUE TITLE
Slash in the nuspec make problems with the nuget installer

### ISSUE THREAD

**Issue by JackGrinningCat** [csoltenborn/GoogleTestAdapter#96]
Hello, 

i tried the newest version as nuget package and besides that installed neatly, when i checked in our CI build had problems because of the LICENCE.txt

I think i found the issue:
https://github.com/csoltenborn/GoogleTestAdapter/blob/master/GoogleTestAdapter/VsPackage/VsPackage.nuspec#L34
is                   `<file src="LICENSE.txt" target="\" />`
should be     `<file src="LICENSE.txt" target="" />`

It's actually not anywhere described good, but here at least is an example without the slash :)
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#adding-a-readme-and-other-files

why i don't make a pull reqeust, i am lazy ;)

**Comment by csoltenborn** [comment]
Hi! Thanks a lot for that pointer - we have in fact seen problems with the nuget package at work (it works on some machines, but not on others), and we have no idea why. This might be the first pointer into the right direction :-)

Documentation is really poor in this area...

**Comment by JackGrinningCat** [comment]
jeah ! :dancing_men:
