### ISSUE TITLE
GTA gets disabled in VS2015

### ISSUE THREAD

**Issue by noizefloor** [csoltenborn/GoogleTestAdapter#98]
Hello,

I'm using GTA 0.8.0.581 on VS 2015 SP2. I've also got Visual Assist 10.9.2118 installed (I'm not sure if that relevant).

Every time I open a Visual Studio project GTA is disabled. I've got to enable it and press restart to get it working again. I think I've seen this problem in earlier versions as well, but with the last version this happens every time.

Other than that GTA works great! Thanks for sharing it with us.

**Comment by csoltenborn** [comment]
We haven't seen problems like that as far as I know... 

There's a couple of suggestions [here](https://github.com/madskristensen/WebEssentials2013/issues/1959) - can you check whether they help? I've just briefly read the issue, but it seems that you want to try cleaning the MEF component cache or make sure that GTA is indeed uninstalled before installing it again... Anyways, it looks like a VS problem, not like a problem of our extension.

Please let us know if anything of the above helped!

**Comment by noizefloor** [comment]
Thanks a lot, that was really helpful. I cleared the MEF cache using "Clear MEF Component Cache" and had to uninstall GTA several times before it was really removed. I cleared the MEF cache again before I reinstalled GTA and now it's working again. I'm not sure if that really the way it should be done...but hey, whatever floats the boat ;)

**Comment by csoltenborn** [comment]
Great, and thanks for letting us know! I'll update our trouble shooting section accordingly...
